#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 96
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 39
#define ALIAS_COUNT 0
#define TOKEN_COUNT 22
#define EXTERNAL_TOKEN_COUNT 4
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define PRODUCTION_ID_COUNT 1

enum ts_symbol_identifiers {
  anon_sym_SLASH = 1,
  anon_sym_SPACE = 2,
  anon_sym_LPAREN = 3,
  anon_sym_RPAREN = 4,
  sym_id = 5,
  sym_name = 6,
  sym_class = 7,
  sym_attribute_name = 8,
  anon_sym_EQ = 9,
  anon_sym_SQUOTE = 10,
  anon_sym_DQUOTE = 11,
  sym__text = 12,
  anon_sym_DASH = 13,
  anon_sym_POUND = 14,
  sym_ruby_expression = 15,
  sym__html_identifier = 16,
  anon_sym_BANG_BANG_BANG = 17,
  sym__newline = 18,
  sym__indent = 19,
  sym__dedent = 20,
  sym_ruby_attributes = 21,
  sym_source_file = 22,
  sym_tag = 23,
  sym__children = 24,
  sym__children_choice = 25,
  sym_html_attributes = 26,
  sym_attributes = 27,
  sym_attribute = 28,
  sym_quoted_attribute_value = 29,
  sym_text_content = 30,
  sym_ruby_block_output = 31,
  sym_ruby_block_run = 32,
  sym_ruby_interpolation = 33,
  sym_doctype = 34,
  aux_sym_source_file_repeat1 = 35,
  aux_sym_tag_repeat1 = 36,
  aux_sym__children_repeat1 = 37,
  aux_sym_html_attributes_repeat1 = 38,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_SLASH] = "self_close_slash",
  [anon_sym_SPACE] = " ",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [sym_id] = "id",
  [sym_name] = "name",
  [sym_class] = "class",
  [sym_attribute_name] = "attribute_name",
  [anon_sym_EQ] = "=",
  [anon_sym_SQUOTE] = "'",
  [anon_sym_DQUOTE] = "\"",
  [sym__text] = "_text",
  [anon_sym_DASH] = "-",
  [anon_sym_POUND] = "#",
  [sym_ruby_expression] = "ruby_expression",
  [sym__html_identifier] = "attribute_value",
  [anon_sym_BANG_BANG_BANG] = "!!!",
  [sym__newline] = "_newline",
  [sym__indent] = "_indent",
  [sym__dedent] = "_dedent",
  [sym_ruby_attributes] = "ruby_attributes",
  [sym_source_file] = "source_file",
  [sym_tag] = "tag",
  [sym__children] = "_children",
  [sym__children_choice] = "_children_choice",
  [sym_html_attributes] = "html_attributes",
  [sym_attributes] = "attributes",
  [sym_attribute] = "attribute",
  [sym_quoted_attribute_value] = "quoted_attribute_value",
  [sym_text_content] = "text_content",
  [sym_ruby_block_output] = "ruby_block_output",
  [sym_ruby_block_run] = "ruby_block_run",
  [sym_ruby_interpolation] = "ruby_interpolation",
  [sym_doctype] = "doctype",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_tag_repeat1] = "tag_repeat1",
  [aux_sym__children_repeat1] = "_children_repeat1",
  [aux_sym_html_attributes_repeat1] = "html_attributes_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_SPACE] = anon_sym_SPACE,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [sym_id] = sym_id,
  [sym_name] = sym_name,
  [sym_class] = sym_class,
  [sym_attribute_name] = sym_attribute_name,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [sym__text] = sym__text,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_POUND] = anon_sym_POUND,
  [sym_ruby_expression] = sym_ruby_expression,
  [sym__html_identifier] = sym__html_identifier,
  [anon_sym_BANG_BANG_BANG] = anon_sym_BANG_BANG_BANG,
  [sym__newline] = sym__newline,
  [sym__indent] = sym__indent,
  [sym__dedent] = sym__dedent,
  [sym_ruby_attributes] = sym_ruby_attributes,
  [sym_source_file] = sym_source_file,
  [sym_tag] = sym_tag,
  [sym__children] = sym__children,
  [sym__children_choice] = sym__children_choice,
  [sym_html_attributes] = sym_html_attributes,
  [sym_attributes] = sym_attributes,
  [sym_attribute] = sym_attribute,
  [sym_quoted_attribute_value] = sym_quoted_attribute_value,
  [sym_text_content] = sym_text_content,
  [sym_ruby_block_output] = sym_ruby_block_output,
  [sym_ruby_block_run] = sym_ruby_block_run,
  [sym_ruby_interpolation] = sym_ruby_interpolation,
  [sym_doctype] = sym_doctype,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_tag_repeat1] = aux_sym_tag_repeat1,
  [aux_sym__children_repeat1] = aux_sym__children_repeat1,
  [aux_sym_html_attributes_repeat1] = aux_sym_html_attributes_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SPACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [sym_id] = {
    .visible = true,
    .named = true,
  },
  [sym_name] = {
    .visible = true,
    .named = true,
  },
  [sym_class] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute_name] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [sym__text] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [sym_ruby_expression] = {
    .visible = true,
    .named = true,
  },
  [sym__html_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_BANG_BANG_BANG] = {
    .visible = true,
    .named = false,
  },
  [sym__newline] = {
    .visible = false,
    .named = true,
  },
  [sym__indent] = {
    .visible = false,
    .named = true,
  },
  [sym__dedent] = {
    .visible = false,
    .named = true,
  },
  [sym_ruby_attributes] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_tag] = {
    .visible = true,
    .named = true,
  },
  [sym__children] = {
    .visible = false,
    .named = true,
  },
  [sym__children_choice] = {
    .visible = false,
    .named = true,
  },
  [sym_html_attributes] = {
    .visible = true,
    .named = true,
  },
  [sym_attributes] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym_quoted_attribute_value] = {
    .visible = true,
    .named = true,
  },
  [sym_text_content] = {
    .visible = true,
    .named = true,
  },
  [sym_ruby_block_output] = {
    .visible = true,
    .named = true,
  },
  [sym_ruby_block_run] = {
    .visible = true,
    .named = true,
  },
  [sym_ruby_interpolation] = {
    .visible = true,
    .named = true,
  },
  [sym_doctype] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_tag_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__children_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_html_attributes_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 2,
  [5] = 5,
  [6] = 6,
  [7] = 5,
  [8] = 6,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 11,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 16,
  [22] = 22,
  [23] = 18,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 17,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 13,
  [34] = 15,
  [35] = 14,
  [36] = 28,
  [37] = 26,
  [38] = 30,
  [39] = 39,
  [40] = 40,
  [41] = 29,
  [42] = 22,
  [43] = 31,
  [44] = 32,
  [45] = 24,
  [46] = 25,
  [47] = 20,
  [48] = 48,
  [49] = 48,
  [50] = 50,
  [51] = 50,
  [52] = 52,
  [53] = 53,
  [54] = 52,
  [55] = 55,
  [56] = 53,
  [57] = 55,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 72,
  [76] = 74,
  [77] = 71,
  [78] = 78,
  [79] = 78,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 83,
  [87] = 84,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 85,
  [92] = 92,
  [93] = 89,
  [94] = 94,
  [95] = 94,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(13);
      ADVANCE_MAP(
        '!', 5,
        '"', 24,
        '#', 28,
        '%', 11,
        '\'', 23,
        '(', 16,
        ')', 17,
        '-', 27,
        '.', 9,
        '/', 14,
        '=', 22,
        '{', 8,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == '\n') SKIP(1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(25);
      if (lookahead != 0) ADVANCE(26);
      END_STATE();
    case 2:
      ADVANCE_MAP(
        ' ', 15,
        '#', 10,
        '%', 11,
        '(', 16,
        '-', 27,
        '.', 9,
        '/', 14,
        '=', 22,
      );
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(2);
      END_STATE();
    case 3:
      if (lookahead == ' ') ADVANCE(15);
      if (lookahead == '#') ADVANCE(12);
      if (lookahead == ')') ADVANCE(17);
      if (lookahead == '=') ADVANCE(22);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(3);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 4:
      if (lookahead == '!') ADVANCE(31);
      END_STATE();
    case 5:
      if (lookahead == '!') ADVANCE(4);
      END_STATE();
    case 6:
      if (lookahead == '"') ADVANCE(24);
      if (lookahead == '\'') ADVANCE(23);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(6);
      if (('-' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(30);
      END_STATE();
    case 7:
      if (lookahead == '#') ADVANCE(12);
      if (lookahead == ')') ADVANCE(17);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(7);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 8:
      if (lookahead == '}') ADVANCE(29);
      if (lookahead != 0) ADVANCE(8);
      END_STATE();
    case 9:
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9')) ADVANCE(9);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 10:
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(18);
      END_STATE();
    case 11:
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(19);
      END_STATE();
    case 12:
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_SPACE);
      if (lookahead == ' ') ADVANCE(15);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_id);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(18);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(19);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_class);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9')) ADVANCE(20);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_attribute_name);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym__text);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(25);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(26);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym__text);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(26);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_POUND);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(18);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_ruby_expression);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym__html_identifier);
      if (('-' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(30);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_BANG_BANG_BANG);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0, .external_lex_state = 2},
  [3] = {.lex_state = 0, .external_lex_state = 2},
  [4] = {.lex_state = 0, .external_lex_state = 2},
  [5] = {.lex_state = 2, .external_lex_state = 3},
  [6] = {.lex_state = 2, .external_lex_state = 3},
  [7] = {.lex_state = 2, .external_lex_state = 3},
  [8] = {.lex_state = 2, .external_lex_state = 3},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0, .external_lex_state = 4},
  [12] = {.lex_state = 0, .external_lex_state = 4},
  [13] = {.lex_state = 0, .external_lex_state = 5},
  [14] = {.lex_state = 0, .external_lex_state = 5},
  [15] = {.lex_state = 0, .external_lex_state = 5},
  [16] = {.lex_state = 0, .external_lex_state = 5},
  [17] = {.lex_state = 0, .external_lex_state = 5},
  [18] = {.lex_state = 0, .external_lex_state = 5},
  [19] = {.lex_state = 2, .external_lex_state = 3},
  [20] = {.lex_state = 0, .external_lex_state = 2},
  [21] = {.lex_state = 0, .external_lex_state = 6},
  [22] = {.lex_state = 0, .external_lex_state = 2},
  [23] = {.lex_state = 0, .external_lex_state = 6},
  [24] = {.lex_state = 0, .external_lex_state = 2},
  [25] = {.lex_state = 0, .external_lex_state = 2},
  [26] = {.lex_state = 0, .external_lex_state = 2},
  [27] = {.lex_state = 0, .external_lex_state = 6},
  [28] = {.lex_state = 0, .external_lex_state = 2},
  [29] = {.lex_state = 0, .external_lex_state = 2},
  [30] = {.lex_state = 0, .external_lex_state = 2},
  [31] = {.lex_state = 0, .external_lex_state = 2},
  [32] = {.lex_state = 0, .external_lex_state = 2},
  [33] = {.lex_state = 0, .external_lex_state = 6},
  [34] = {.lex_state = 0, .external_lex_state = 6},
  [35] = {.lex_state = 0, .external_lex_state = 6},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 2, .external_lex_state = 4},
  [49] = {.lex_state = 2, .external_lex_state = 4},
  [50] = {.lex_state = 2, .external_lex_state = 4},
  [51] = {.lex_state = 2, .external_lex_state = 4},
  [52] = {.lex_state = 2, .external_lex_state = 4},
  [53] = {.lex_state = 2, .external_lex_state = 4},
  [54] = {.lex_state = 2, .external_lex_state = 4},
  [55] = {.lex_state = 2, .external_lex_state = 4},
  [56] = {.lex_state = 2, .external_lex_state = 4},
  [57] = {.lex_state = 2, .external_lex_state = 4},
  [58] = {.lex_state = 2, .external_lex_state = 4},
  [59] = {.lex_state = 2, .external_lex_state = 4},
  [60] = {.lex_state = 2, .external_lex_state = 4},
  [61] = {.lex_state = 7},
  [62] = {.lex_state = 7},
  [63] = {.lex_state = 3},
  [64] = {.lex_state = 7},
  [65] = {.lex_state = 3},
  [66] = {.lex_state = 3},
  [67] = {.lex_state = 3},
  [68] = {.lex_state = 3},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 6},
  [71] = {.lex_state = 1},
  [72] = {.lex_state = 1},
  [73] = {.lex_state = 7},
  [74] = {.lex_state = 1},
  [75] = {.lex_state = 1},
  [76] = {.lex_state = 1},
  [77] = {.lex_state = 1},
  [78] = {.lex_state = 1},
  [79] = {.lex_state = 1},
  [80] = {.lex_state = 1, .external_lex_state = 4},
  [81] = {.lex_state = 6},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0, .external_lex_state = 4},
  [84] = {.lex_state = 0, .external_lex_state = 4},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0, .external_lex_state = 4},
  [87] = {.lex_state = 0, .external_lex_state = 4},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 1},
  [90] = {.lex_state = 0, .external_lex_state = 4},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 1},
  [94] = {.lex_state = 1},
  [95] = {.lex_state = 1},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [sym_id] = ACTIONS(1),
    [sym_name] = ACTIONS(1),
    [sym_class] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(1),
    [sym_ruby_expression] = ACTIONS(1),
    [anon_sym_BANG_BANG_BANG] = ACTIONS(1),
    [sym__newline] = ACTIONS(1),
    [sym__indent] = ACTIONS(1),
    [sym__dedent] = ACTIONS(1),
    [sym_ruby_attributes] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(88),
    [sym_tag] = STATE(9),
    [sym_ruby_block_output] = STATE(9),
    [sym_ruby_block_run] = STATE(9),
    [sym_ruby_interpolation] = STATE(9),
    [sym_doctype] = STATE(9),
    [aux_sym_source_file_repeat1] = STATE(9),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_id] = ACTIONS(5),
    [sym_name] = ACTIONS(5),
    [sym_class] = ACTIONS(5),
    [anon_sym_EQ] = ACTIONS(7),
    [anon_sym_DASH] = ACTIONS(9),
    [anon_sym_POUND] = ACTIONS(11),
    [anon_sym_BANG_BANG_BANG] = ACTIONS(13),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 8,
    ACTIONS(19), 1,
      anon_sym_EQ,
    ACTIONS(21), 1,
      anon_sym_DASH,
    ACTIONS(23), 1,
      anon_sym_POUND,
    ACTIONS(25), 1,
      sym__newline,
    ACTIONS(27), 1,
      sym__dedent,
    ACTIONS(15), 2,
      ts_builtin_sym_end,
      anon_sym_BANG_BANG_BANG,
    ACTIONS(17), 3,
      sym_id,
      sym_name,
      sym_class,
    STATE(3), 6,
      sym_tag,
      sym__children_choice,
      sym_ruby_block_output,
      sym_ruby_block_run,
      sym_ruby_interpolation,
      aux_sym__children_repeat1,
  [33] = 7,
    ACTIONS(34), 1,
      anon_sym_EQ,
    ACTIONS(37), 1,
      anon_sym_DASH,
    ACTIONS(40), 1,
      anon_sym_POUND,
    ACTIONS(43), 1,
      sym__newline,
    ACTIONS(29), 3,
      sym__dedent,
      ts_builtin_sym_end,
      anon_sym_BANG_BANG_BANG,
    ACTIONS(31), 3,
      sym_id,
      sym_name,
      sym_class,
    STATE(3), 6,
      sym_tag,
      sym__children_choice,
      sym_ruby_block_output,
      sym_ruby_block_run,
      sym_ruby_interpolation,
      aux_sym__children_repeat1,
  [64] = 8,
    ACTIONS(19), 1,
      anon_sym_EQ,
    ACTIONS(21), 1,
      anon_sym_DASH,
    ACTIONS(23), 1,
      anon_sym_POUND,
    ACTIONS(25), 1,
      sym__newline,
    ACTIONS(46), 1,
      sym__dedent,
    ACTIONS(15), 2,
      ts_builtin_sym_end,
      anon_sym_BANG_BANG_BANG,
    ACTIONS(17), 3,
      sym_id,
      sym_name,
      sym_class,
    STATE(3), 6,
      sym_tag,
      sym__children_choice,
      sym_ruby_block_output,
      sym_ruby_block_run,
      sym_ruby_interpolation,
      aux_sym__children_repeat1,
  [97] = 12,
    ACTIONS(48), 1,
      anon_sym_SLASH,
    ACTIONS(50), 1,
      anon_sym_SPACE,
    ACTIONS(52), 1,
      anon_sym_LPAREN,
    ACTIONS(56), 1,
      anon_sym_EQ,
    ACTIONS(58), 1,
      anon_sym_DASH,
    ACTIONS(60), 1,
      sym__newline,
    ACTIONS(62), 1,
      sym_ruby_attributes,
    STATE(8), 1,
      aux_sym_tag_repeat1,
    STATE(51), 1,
      sym_attributes,
    STATE(58), 1,
      sym_html_attributes,
    STATE(44), 2,
      sym_ruby_block_output,
      sym_ruby_block_run,
    ACTIONS(54), 3,
      sym_id,
      sym_name,
      sym_class,
  [137] = 12,
    ACTIONS(52), 1,
      anon_sym_LPAREN,
    ACTIONS(62), 1,
      sym_ruby_attributes,
    ACTIONS(64), 1,
      anon_sym_SLASH,
    ACTIONS(66), 1,
      anon_sym_SPACE,
    ACTIONS(70), 1,
      anon_sym_EQ,
    ACTIONS(72), 1,
      anon_sym_DASH,
    ACTIONS(74), 1,
      sym__newline,
    STATE(19), 1,
      aux_sym_tag_repeat1,
    STATE(48), 1,
      sym_attributes,
    STATE(58), 1,
      sym_html_attributes,
    STATE(30), 2,
      sym_ruby_block_output,
      sym_ruby_block_run,
    ACTIONS(68), 3,
      sym_id,
      sym_name,
      sym_class,
  [177] = 12,
    ACTIONS(52), 1,
      anon_sym_LPAREN,
    ACTIONS(62), 1,
      sym_ruby_attributes,
    ACTIONS(70), 1,
      anon_sym_EQ,
    ACTIONS(72), 1,
      anon_sym_DASH,
    ACTIONS(76), 1,
      anon_sym_SLASH,
    ACTIONS(78), 1,
      anon_sym_SPACE,
    ACTIONS(82), 1,
      sym__newline,
    STATE(6), 1,
      aux_sym_tag_repeat1,
    STATE(50), 1,
      sym_attributes,
    STATE(58), 1,
      sym_html_attributes,
    STATE(32), 2,
      sym_ruby_block_output,
      sym_ruby_block_run,
    ACTIONS(80), 3,
      sym_id,
      sym_name,
      sym_class,
  [217] = 12,
    ACTIONS(52), 1,
      anon_sym_LPAREN,
    ACTIONS(56), 1,
      anon_sym_EQ,
    ACTIONS(58), 1,
      anon_sym_DASH,
    ACTIONS(62), 1,
      sym_ruby_attributes,
    ACTIONS(84), 1,
      anon_sym_SLASH,
    ACTIONS(86), 1,
      anon_sym_SPACE,
    ACTIONS(88), 1,
      sym__newline,
    STATE(19), 1,
      aux_sym_tag_repeat1,
    STATE(49), 1,
      sym_attributes,
    STATE(58), 1,
      sym_html_attributes,
    STATE(38), 2,
      sym_ruby_block_output,
      sym_ruby_block_run,
    ACTIONS(68), 3,
      sym_id,
      sym_name,
      sym_class,
  [257] = 7,
    ACTIONS(7), 1,
      anon_sym_EQ,
    ACTIONS(9), 1,
      anon_sym_DASH,
    ACTIONS(11), 1,
      anon_sym_POUND,
    ACTIONS(13), 1,
      anon_sym_BANG_BANG_BANG,
    ACTIONS(90), 1,
      ts_builtin_sym_end,
    ACTIONS(5), 3,
      sym_id,
      sym_name,
      sym_class,
    STATE(10), 6,
      sym_tag,
      sym_ruby_block_output,
      sym_ruby_block_run,
      sym_ruby_interpolation,
      sym_doctype,
      aux_sym_source_file_repeat1,
  [286] = 7,
    ACTIONS(92), 1,
      ts_builtin_sym_end,
    ACTIONS(97), 1,
      anon_sym_EQ,
    ACTIONS(100), 1,
      anon_sym_DASH,
    ACTIONS(103), 1,
      anon_sym_POUND,
    ACTIONS(106), 1,
      anon_sym_BANG_BANG_BANG,
    ACTIONS(94), 3,
      sym_id,
      sym_name,
      sym_class,
    STATE(10), 6,
      sym_tag,
      sym_ruby_block_output,
      sym_ruby_block_run,
      sym_ruby_interpolation,
      sym_doctype,
      aux_sym_source_file_repeat1,
  [315] = 6,
    ACTIONS(19), 1,
      anon_sym_EQ,
    ACTIONS(21), 1,
      anon_sym_DASH,
    ACTIONS(23), 1,
      anon_sym_POUND,
    ACTIONS(109), 1,
      sym__newline,
    ACTIONS(17), 3,
      sym_id,
      sym_name,
      sym_class,
    STATE(2), 6,
      sym_tag,
      sym__children_choice,
      sym_ruby_block_output,
      sym_ruby_block_run,
      sym_ruby_interpolation,
      aux_sym__children_repeat1,
  [341] = 6,
    ACTIONS(19), 1,
      anon_sym_EQ,
    ACTIONS(21), 1,
      anon_sym_DASH,
    ACTIONS(23), 1,
      anon_sym_POUND,
    ACTIONS(111), 1,
      sym__newline,
    ACTIONS(17), 3,
      sym_id,
      sym_name,
      sym_class,
    STATE(4), 6,
      sym_tag,
      sym__children_choice,
      sym_ruby_block_output,
      sym_ruby_block_run,
      sym_ruby_interpolation,
      aux_sym__children_repeat1,
  [367] = 4,
    ACTIONS(115), 1,
      anon_sym_POUND,
    ACTIONS(117), 1,
      sym__indent,
    STATE(22), 1,
      sym__children,
    ACTIONS(113), 9,
      sym__newline,
      sym__dedent,
      ts_builtin_sym_end,
      sym_id,
      sym_name,
      sym_class,
      anon_sym_EQ,
      anon_sym_DASH,
      anon_sym_BANG_BANG_BANG,
  [388] = 4,
    ACTIONS(117), 1,
      sym__indent,
    ACTIONS(121), 1,
      anon_sym_POUND,
    STATE(24), 1,
      sym__children,
    ACTIONS(119), 9,
      sym__newline,
      sym__dedent,
      ts_builtin_sym_end,
      sym_id,
      sym_name,
      sym_class,
      anon_sym_EQ,
      anon_sym_DASH,
      anon_sym_BANG_BANG_BANG,
  [409] = 4,
    ACTIONS(117), 1,
      sym__indent,
    ACTIONS(125), 1,
      anon_sym_POUND,
    STATE(26), 1,
      sym__children,
    ACTIONS(123), 9,
      sym__newline,
      sym__dedent,
      ts_builtin_sym_end,
      sym_id,
      sym_name,
      sym_class,
      anon_sym_EQ,
      anon_sym_DASH,
      anon_sym_BANG_BANG_BANG,
  [430] = 4,
    ACTIONS(117), 1,
      sym__indent,
    ACTIONS(129), 1,
      anon_sym_POUND,
    STATE(20), 1,
      sym__children,
    ACTIONS(127), 9,
      sym__newline,
      sym__dedent,
      ts_builtin_sym_end,
      sym_id,
      sym_name,
      sym_class,
      anon_sym_EQ,
      anon_sym_DASH,
      anon_sym_BANG_BANG_BANG,
  [451] = 4,
    ACTIONS(117), 1,
      sym__indent,
    ACTIONS(133), 1,
      anon_sym_POUND,
    STATE(28), 1,
      sym__children,
    ACTIONS(131), 9,
      sym__newline,
      sym__dedent,
      ts_builtin_sym_end,
      sym_id,
      sym_name,
      sym_class,
      anon_sym_EQ,
      anon_sym_DASH,
      anon_sym_BANG_BANG_BANG,
  [472] = 4,
    ACTIONS(117), 1,
      sym__indent,
    ACTIONS(137), 1,
      anon_sym_POUND,
    STATE(30), 1,
      sym__children,
    ACTIONS(135), 9,
      sym__newline,
      sym__dedent,
      ts_builtin_sym_end,
      sym_id,
      sym_name,
      sym_class,
      anon_sym_EQ,
      anon_sym_DASH,
      anon_sym_BANG_BANG_BANG,
  [493] = 4,
    STATE(19), 1,
      aux_sym_tag_repeat1,
    ACTIONS(141), 3,
      sym__newline,
      sym_ruby_attributes,
      anon_sym_SPACE,
    ACTIONS(143), 3,
      sym_id,
      sym_name,
      sym_class,
    ACTIONS(139), 4,
      anon_sym_SLASH,
      anon_sym_LPAREN,
      anon_sym_EQ,
      anon_sym_DASH,
  [513] = 2,
    ACTIONS(148), 1,
      anon_sym_POUND,
    ACTIONS(146), 9,
      sym__newline,
      sym__dedent,
      ts_builtin_sym_end,
      sym_id,
      sym_name,
      sym_class,
      anon_sym_EQ,
      anon_sym_DASH,
      anon_sym_BANG_BANG_BANG,
  [528] = 4,
    ACTIONS(129), 1,
      anon_sym_POUND,
    ACTIONS(150), 1,
      sym__indent,
    STATE(47), 1,
      sym__children,
    ACTIONS(127), 7,
      ts_builtin_sym_end,
      sym_id,
      sym_name,
      sym_class,
      anon_sym_EQ,
      anon_sym_DASH,
      anon_sym_BANG_BANG_BANG,
  [547] = 2,
    ACTIONS(154), 1,
      anon_sym_POUND,
    ACTIONS(152), 9,
      sym__newline,
      sym__dedent,
      ts_builtin_sym_end,
      sym_id,
      sym_name,
      sym_class,
      anon_sym_EQ,
      anon_sym_DASH,
      anon_sym_BANG_BANG_BANG,
  [562] = 4,
    ACTIONS(137), 1,
      anon_sym_POUND,
    ACTIONS(150), 1,
      sym__indent,
    STATE(38), 1,
      sym__children,
    ACTIONS(135), 7,
      ts_builtin_sym_end,
      sym_id,
      sym_name,
      sym_class,
      anon_sym_EQ,
      anon_sym_DASH,
      anon_sym_BANG_BANG_BANG,
  [581] = 2,
    ACTIONS(115), 1,
      anon_sym_POUND,
    ACTIONS(113), 9,
      sym__newline,
      sym__dedent,
      ts_builtin_sym_end,
      sym_id,
      sym_name,
      sym_class,
      anon_sym_EQ,
      anon_sym_DASH,
      anon_sym_BANG_BANG_BANG,
  [596] = 2,
    ACTIONS(158), 1,
      anon_sym_POUND,
    ACTIONS(156), 9,
      sym__newline,
      sym__dedent,
      ts_builtin_sym_end,
      sym_id,
      sym_name,
      sym_class,
      anon_sym_EQ,
      anon_sym_DASH,
      anon_sym_BANG_BANG_BANG,
  [611] = 2,
    ACTIONS(162), 1,
      anon_sym_POUND,
    ACTIONS(160), 9,
      sym__newline,
      sym__dedent,
      ts_builtin_sym_end,
      sym_id,
      sym_name,
      sym_class,
      anon_sym_EQ,
      anon_sym_DASH,
      anon_sym_BANG_BANG_BANG,
  [626] = 4,
    ACTIONS(133), 1,
      anon_sym_POUND,
    ACTIONS(150), 1,
      sym__indent,
    STATE(36), 1,
      sym__children,
    ACTIONS(131), 7,
      ts_builtin_sym_end,
      sym_id,
      sym_name,
      sym_class,
      anon_sym_EQ,
      anon_sym_DASH,
      anon_sym_BANG_BANG_BANG,
  [645] = 2,
    ACTIONS(121), 1,
      anon_sym_POUND,
    ACTIONS(119), 9,
      sym__newline,
      sym__dedent,
      ts_builtin_sym_end,
      sym_id,
      sym_name,
      sym_class,
      anon_sym_EQ,
      anon_sym_DASH,
      anon_sym_BANG_BANG_BANG,
  [660] = 2,
    ACTIONS(166), 1,
      anon_sym_POUND,
    ACTIONS(164), 9,
      sym__newline,
      sym__dedent,
      ts_builtin_sym_end,
      sym_id,
      sym_name,
      sym_class,
      anon_sym_EQ,
      anon_sym_DASH,
      anon_sym_BANG_BANG_BANG,
  [675] = 2,
    ACTIONS(133), 1,
      anon_sym_POUND,
    ACTIONS(131), 9,
      sym__newline,
      sym__dedent,
      ts_builtin_sym_end,
      sym_id,
      sym_name,
      sym_class,
      anon_sym_EQ,
      anon_sym_DASH,
      anon_sym_BANG_BANG_BANG,
  [690] = 2,
    ACTIONS(170), 1,
      anon_sym_POUND,
    ACTIONS(168), 9,
      sym__newline,
      sym__dedent,
      ts_builtin_sym_end,
      sym_id,
      sym_name,
      sym_class,
      anon_sym_EQ,
      anon_sym_DASH,
      anon_sym_BANG_BANG_BANG,
  [705] = 2,
    ACTIONS(137), 1,
      anon_sym_POUND,
    ACTIONS(135), 9,
      sym__newline,
      sym__dedent,
      ts_builtin_sym_end,
      sym_id,
      sym_name,
      sym_class,
      anon_sym_EQ,
      anon_sym_DASH,
      anon_sym_BANG_BANG_BANG,
  [720] = 4,
    ACTIONS(115), 1,
      anon_sym_POUND,
    ACTIONS(150), 1,
      sym__indent,
    STATE(42), 1,
      sym__children,
    ACTIONS(113), 7,
      ts_builtin_sym_end,
      sym_id,
      sym_name,
      sym_class,
      anon_sym_EQ,
      anon_sym_DASH,
      anon_sym_BANG_BANG_BANG,
  [739] = 4,
    ACTIONS(125), 1,
      anon_sym_POUND,
    ACTIONS(150), 1,
      sym__indent,
    STATE(37), 1,
      sym__children,
    ACTIONS(123), 7,
      ts_builtin_sym_end,
      sym_id,
      sym_name,
      sym_class,
      anon_sym_EQ,
      anon_sym_DASH,
      anon_sym_BANG_BANG_BANG,
  [758] = 4,
    ACTIONS(121), 1,
      anon_sym_POUND,
    ACTIONS(150), 1,
      sym__indent,
    STATE(45), 1,
      sym__children,
    ACTIONS(119), 7,
      ts_builtin_sym_end,
      sym_id,
      sym_name,
      sym_class,
      anon_sym_EQ,
      anon_sym_DASH,
      anon_sym_BANG_BANG_BANG,
  [777] = 2,
    ACTIONS(121), 1,
      anon_sym_POUND,
    ACTIONS(119), 7,
      ts_builtin_sym_end,
      sym_id,
      sym_name,
      sym_class,
      anon_sym_EQ,
      anon_sym_DASH,
      anon_sym_BANG_BANG_BANG,
  [790] = 2,
    ACTIONS(162), 1,
      anon_sym_POUND,
    ACTIONS(160), 7,
      ts_builtin_sym_end,
      sym_id,
      sym_name,
      sym_class,
      anon_sym_EQ,
      anon_sym_DASH,
      anon_sym_BANG_BANG_BANG,
  [803] = 2,
    ACTIONS(133), 1,
      anon_sym_POUND,
    ACTIONS(131), 7,
      ts_builtin_sym_end,
      sym_id,
      sym_name,
      sym_class,
      anon_sym_EQ,
      anon_sym_DASH,
      anon_sym_BANG_BANG_BANG,
  [816] = 2,
    ACTIONS(174), 1,
      anon_sym_POUND,
    ACTIONS(172), 7,
      ts_builtin_sym_end,
      sym_id,
      sym_name,
      sym_class,
      anon_sym_EQ,
      anon_sym_DASH,
      anon_sym_BANG_BANG_BANG,
  [829] = 2,
    ACTIONS(178), 1,
      anon_sym_POUND,
    ACTIONS(176), 7,
      ts_builtin_sym_end,
      sym_id,
      sym_name,
      sym_class,
      anon_sym_EQ,
      anon_sym_DASH,
      anon_sym_BANG_BANG_BANG,
  [842] = 2,
    ACTIONS(166), 1,
      anon_sym_POUND,
    ACTIONS(164), 7,
      ts_builtin_sym_end,
      sym_id,
      sym_name,
      sym_class,
      anon_sym_EQ,
      anon_sym_DASH,
      anon_sym_BANG_BANG_BANG,
  [855] = 2,
    ACTIONS(154), 1,
      anon_sym_POUND,
    ACTIONS(152), 7,
      ts_builtin_sym_end,
      sym_id,
      sym_name,
      sym_class,
      anon_sym_EQ,
      anon_sym_DASH,
      anon_sym_BANG_BANG_BANG,
  [868] = 2,
    ACTIONS(170), 1,
      anon_sym_POUND,
    ACTIONS(168), 7,
      ts_builtin_sym_end,
      sym_id,
      sym_name,
      sym_class,
      anon_sym_EQ,
      anon_sym_DASH,
      anon_sym_BANG_BANG_BANG,
  [881] = 2,
    ACTIONS(137), 1,
      anon_sym_POUND,
    ACTIONS(135), 7,
      ts_builtin_sym_end,
      sym_id,
      sym_name,
      sym_class,
      anon_sym_EQ,
      anon_sym_DASH,
      anon_sym_BANG_BANG_BANG,
  [894] = 2,
    ACTIONS(115), 1,
      anon_sym_POUND,
    ACTIONS(113), 7,
      ts_builtin_sym_end,
      sym_id,
      sym_name,
      sym_class,
      anon_sym_EQ,
      anon_sym_DASH,
      anon_sym_BANG_BANG_BANG,
  [907] = 2,
    ACTIONS(158), 1,
      anon_sym_POUND,
    ACTIONS(156), 7,
      ts_builtin_sym_end,
      sym_id,
      sym_name,
      sym_class,
      anon_sym_EQ,
      anon_sym_DASH,
      anon_sym_BANG_BANG_BANG,
  [920] = 2,
    ACTIONS(148), 1,
      anon_sym_POUND,
    ACTIONS(146), 7,
      ts_builtin_sym_end,
      sym_id,
      sym_name,
      sym_class,
      anon_sym_EQ,
      anon_sym_DASH,
      anon_sym_BANG_BANG_BANG,
  [933] = 6,
    ACTIONS(70), 1,
      anon_sym_EQ,
    ACTIONS(72), 1,
      anon_sym_DASH,
    ACTIONS(180), 1,
      anon_sym_SLASH,
    ACTIONS(182), 1,
      anon_sym_SPACE,
    ACTIONS(184), 1,
      sym__newline,
    STATE(28), 2,
      sym_ruby_block_output,
      sym_ruby_block_run,
  [953] = 6,
    ACTIONS(56), 1,
      anon_sym_EQ,
    ACTIONS(58), 1,
      anon_sym_DASH,
    ACTIONS(186), 1,
      anon_sym_SLASH,
    ACTIONS(188), 1,
      anon_sym_SPACE,
    ACTIONS(190), 1,
      sym__newline,
    STATE(36), 2,
      sym_ruby_block_output,
      sym_ruby_block_run,
  [973] = 6,
    ACTIONS(64), 1,
      anon_sym_SLASH,
    ACTIONS(66), 1,
      anon_sym_SPACE,
    ACTIONS(70), 1,
      anon_sym_EQ,
    ACTIONS(72), 1,
      anon_sym_DASH,
    ACTIONS(74), 1,
      sym__newline,
    STATE(30), 2,
      sym_ruby_block_output,
      sym_ruby_block_run,
  [993] = 6,
    ACTIONS(56), 1,
      anon_sym_EQ,
    ACTIONS(58), 1,
      anon_sym_DASH,
    ACTIONS(84), 1,
      anon_sym_SLASH,
    ACTIONS(86), 1,
      anon_sym_SPACE,
    ACTIONS(88), 1,
      sym__newline,
    STATE(38), 2,
      sym_ruby_block_output,
      sym_ruby_block_run,
  [1013] = 5,
    ACTIONS(66), 1,
      anon_sym_SPACE,
    ACTIONS(70), 1,
      anon_sym_EQ,
    ACTIONS(72), 1,
      anon_sym_DASH,
    ACTIONS(74), 1,
      sym__newline,
    STATE(30), 2,
      sym_ruby_block_output,
      sym_ruby_block_run,
  [1030] = 5,
    ACTIONS(56), 1,
      anon_sym_EQ,
    ACTIONS(58), 1,
      anon_sym_DASH,
    ACTIONS(188), 1,
      anon_sym_SPACE,
    ACTIONS(190), 1,
      sym__newline,
    STATE(36), 2,
      sym_ruby_block_output,
      sym_ruby_block_run,
  [1047] = 5,
    ACTIONS(56), 1,
      anon_sym_EQ,
    ACTIONS(58), 1,
      anon_sym_DASH,
    ACTIONS(86), 1,
      anon_sym_SPACE,
    ACTIONS(88), 1,
      sym__newline,
    STATE(38), 2,
      sym_ruby_block_output,
      sym_ruby_block_run,
  [1064] = 5,
    ACTIONS(56), 1,
      anon_sym_EQ,
    ACTIONS(58), 1,
      anon_sym_DASH,
    ACTIONS(192), 1,
      anon_sym_SPACE,
    ACTIONS(194), 1,
      sym__newline,
    STATE(45), 2,
      sym_ruby_block_output,
      sym_ruby_block_run,
  [1081] = 5,
    ACTIONS(70), 1,
      anon_sym_EQ,
    ACTIONS(72), 1,
      anon_sym_DASH,
    ACTIONS(182), 1,
      anon_sym_SPACE,
    ACTIONS(184), 1,
      sym__newline,
    STATE(28), 2,
      sym_ruby_block_output,
      sym_ruby_block_run,
  [1098] = 5,
    ACTIONS(70), 1,
      anon_sym_EQ,
    ACTIONS(72), 1,
      anon_sym_DASH,
    ACTIONS(196), 1,
      anon_sym_SPACE,
    ACTIONS(198), 1,
      sym__newline,
    STATE(24), 2,
      sym_ruby_block_output,
      sym_ruby_block_run,
  [1115] = 2,
    ACTIONS(202), 2,
      sym__newline,
      anon_sym_SPACE,
    ACTIONS(200), 3,
      anon_sym_SLASH,
      anon_sym_EQ,
      anon_sym_DASH,
  [1125] = 2,
    ACTIONS(206), 2,
      sym__newline,
      anon_sym_SPACE,
    ACTIONS(204), 3,
      anon_sym_SLASH,
      anon_sym_EQ,
      anon_sym_DASH,
  [1135] = 2,
    ACTIONS(210), 2,
      sym__newline,
      anon_sym_SPACE,
    ACTIONS(208), 3,
      anon_sym_SLASH,
      anon_sym_EQ,
      anon_sym_DASH,
  [1145] = 4,
    ACTIONS(212), 1,
      anon_sym_RPAREN,
    ACTIONS(214), 1,
      sym_attribute_name,
    STATE(62), 1,
      aux_sym_html_attributes_repeat1,
    STATE(67), 1,
      sym_attribute,
  [1158] = 4,
    ACTIONS(214), 1,
      sym_attribute_name,
    ACTIONS(216), 1,
      anon_sym_RPAREN,
    STATE(64), 1,
      aux_sym_html_attributes_repeat1,
    STATE(67), 1,
      sym_attribute,
  [1171] = 3,
    ACTIONS(218), 1,
      anon_sym_SPACE,
    ACTIONS(222), 1,
      anon_sym_EQ,
    ACTIONS(220), 2,
      anon_sym_RPAREN,
      sym_attribute_name,
  [1182] = 4,
    ACTIONS(224), 1,
      anon_sym_RPAREN,
    ACTIONS(226), 1,
      sym_attribute_name,
    STATE(64), 1,
      aux_sym_html_attributes_repeat1,
    STATE(67), 1,
      sym_attribute,
  [1195] = 2,
    ACTIONS(229), 1,
      anon_sym_SPACE,
    ACTIONS(231), 2,
      anon_sym_RPAREN,
      sym_attribute_name,
  [1203] = 2,
    ACTIONS(233), 1,
      anon_sym_SPACE,
    ACTIONS(235), 2,
      anon_sym_RPAREN,
      sym_attribute_name,
  [1211] = 2,
    ACTIONS(237), 1,
      anon_sym_SPACE,
    ACTIONS(239), 2,
      anon_sym_RPAREN,
      sym_attribute_name,
  [1219] = 2,
    ACTIONS(241), 1,
      anon_sym_SPACE,
    ACTIONS(243), 2,
      anon_sym_RPAREN,
      sym_attribute_name,
  [1227] = 3,
    ACTIONS(245), 1,
      anon_sym_SQUOTE,
    ACTIONS(247), 1,
      anon_sym_DQUOTE,
    STATE(65), 1,
      sym_quoted_attribute_value,
  [1237] = 2,
    ACTIONS(249), 1,
      anon_sym_DQUOTE,
    ACTIONS(251), 1,
      sym__html_identifier,
  [1244] = 2,
    ACTIONS(253), 1,
      sym__text,
    STATE(30), 1,
      sym_text_content,
  [1251] = 2,
    ACTIONS(253), 1,
      sym__text,
    STATE(24), 1,
      sym_text_content,
  [1258] = 1,
    ACTIONS(224), 2,
      anon_sym_RPAREN,
      sym_attribute_name,
  [1263] = 2,
    ACTIONS(255), 1,
      sym__text,
    STATE(36), 1,
      sym_text_content,
  [1270] = 2,
    ACTIONS(255), 1,
      sym__text,
    STATE(45), 1,
      sym_text_content,
  [1277] = 2,
    ACTIONS(253), 1,
      sym__text,
    STATE(28), 1,
      sym_text_content,
  [1284] = 2,
    ACTIONS(255), 1,
      sym__text,
    STATE(38), 1,
      sym_text_content,
  [1291] = 2,
    ACTIONS(253), 1,
      sym__text,
    STATE(22), 1,
      sym_text_content,
  [1298] = 2,
    ACTIONS(255), 1,
      sym__text,
    STATE(42), 1,
      sym_text_content,
  [1305] = 2,
    ACTIONS(257), 1,
      sym__text,
    ACTIONS(259), 1,
      sym__newline,
  [1312] = 2,
    ACTIONS(249), 1,
      anon_sym_SQUOTE,
    ACTIONS(261), 1,
      sym__html_identifier,
  [1319] = 1,
    ACTIONS(263), 1,
      anon_sym_SQUOTE,
  [1323] = 1,
    ACTIONS(265), 1,
      sym__newline,
  [1327] = 1,
    ACTIONS(267), 1,
      sym__newline,
  [1331] = 1,
    ACTIONS(269), 1,
      sym_ruby_expression,
  [1335] = 1,
    ACTIONS(271), 1,
      sym__newline,
  [1339] = 1,
    ACTIONS(273), 1,
      sym__newline,
  [1343] = 1,
    ACTIONS(275), 1,
      ts_builtin_sym_end,
  [1347] = 1,
    ACTIONS(277), 1,
      sym__text,
  [1351] = 1,
    ACTIONS(279), 1,
      sym__newline,
  [1355] = 1,
    ACTIONS(281), 1,
      sym_ruby_expression,
  [1359] = 1,
    ACTIONS(263), 1,
      anon_sym_DQUOTE,
  [1363] = 1,
    ACTIONS(283), 1,
      sym__text,
  [1367] = 1,
    ACTIONS(285), 1,
      sym__text,
  [1371] = 1,
    ACTIONS(287), 1,
      sym__text,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 33,
  [SMALL_STATE(4)] = 64,
  [SMALL_STATE(5)] = 97,
  [SMALL_STATE(6)] = 137,
  [SMALL_STATE(7)] = 177,
  [SMALL_STATE(8)] = 217,
  [SMALL_STATE(9)] = 257,
  [SMALL_STATE(10)] = 286,
  [SMALL_STATE(11)] = 315,
  [SMALL_STATE(12)] = 341,
  [SMALL_STATE(13)] = 367,
  [SMALL_STATE(14)] = 388,
  [SMALL_STATE(15)] = 409,
  [SMALL_STATE(16)] = 430,
  [SMALL_STATE(17)] = 451,
  [SMALL_STATE(18)] = 472,
  [SMALL_STATE(19)] = 493,
  [SMALL_STATE(20)] = 513,
  [SMALL_STATE(21)] = 528,
  [SMALL_STATE(22)] = 547,
  [SMALL_STATE(23)] = 562,
  [SMALL_STATE(24)] = 581,
  [SMALL_STATE(25)] = 596,
  [SMALL_STATE(26)] = 611,
  [SMALL_STATE(27)] = 626,
  [SMALL_STATE(28)] = 645,
  [SMALL_STATE(29)] = 660,
  [SMALL_STATE(30)] = 675,
  [SMALL_STATE(31)] = 690,
  [SMALL_STATE(32)] = 705,
  [SMALL_STATE(33)] = 720,
  [SMALL_STATE(34)] = 739,
  [SMALL_STATE(35)] = 758,
  [SMALL_STATE(36)] = 777,
  [SMALL_STATE(37)] = 790,
  [SMALL_STATE(38)] = 803,
  [SMALL_STATE(39)] = 816,
  [SMALL_STATE(40)] = 829,
  [SMALL_STATE(41)] = 842,
  [SMALL_STATE(42)] = 855,
  [SMALL_STATE(43)] = 868,
  [SMALL_STATE(44)] = 881,
  [SMALL_STATE(45)] = 894,
  [SMALL_STATE(46)] = 907,
  [SMALL_STATE(47)] = 920,
  [SMALL_STATE(48)] = 933,
  [SMALL_STATE(49)] = 953,
  [SMALL_STATE(50)] = 973,
  [SMALL_STATE(51)] = 993,
  [SMALL_STATE(52)] = 1013,
  [SMALL_STATE(53)] = 1030,
  [SMALL_STATE(54)] = 1047,
  [SMALL_STATE(55)] = 1064,
  [SMALL_STATE(56)] = 1081,
  [SMALL_STATE(57)] = 1098,
  [SMALL_STATE(58)] = 1115,
  [SMALL_STATE(59)] = 1125,
  [SMALL_STATE(60)] = 1135,
  [SMALL_STATE(61)] = 1145,
  [SMALL_STATE(62)] = 1158,
  [SMALL_STATE(63)] = 1171,
  [SMALL_STATE(64)] = 1182,
  [SMALL_STATE(65)] = 1195,
  [SMALL_STATE(66)] = 1203,
  [SMALL_STATE(67)] = 1211,
  [SMALL_STATE(68)] = 1219,
  [SMALL_STATE(69)] = 1227,
  [SMALL_STATE(70)] = 1237,
  [SMALL_STATE(71)] = 1244,
  [SMALL_STATE(72)] = 1251,
  [SMALL_STATE(73)] = 1258,
  [SMALL_STATE(74)] = 1263,
  [SMALL_STATE(75)] = 1270,
  [SMALL_STATE(76)] = 1277,
  [SMALL_STATE(77)] = 1284,
  [SMALL_STATE(78)] = 1291,
  [SMALL_STATE(79)] = 1298,
  [SMALL_STATE(80)] = 1305,
  [SMALL_STATE(81)] = 1312,
  [SMALL_STATE(82)] = 1319,
  [SMALL_STATE(83)] = 1323,
  [SMALL_STATE(84)] = 1327,
  [SMALL_STATE(85)] = 1331,
  [SMALL_STATE(86)] = 1335,
  [SMALL_STATE(87)] = 1339,
  [SMALL_STATE(88)] = 1343,
  [SMALL_STATE(89)] = 1347,
  [SMALL_STATE(90)] = 1351,
  [SMALL_STATE(91)] = 1355,
  [SMALL_STATE(92)] = 1359,
  [SMALL_STATE(93)] = 1363,
  [SMALL_STATE(94)] = 1367,
  [SMALL_STATE(95)] = 1371,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(91),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__children, 2, 0, 0),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(85),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__children_repeat1, 2, 0, 0),
  [31] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__children_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [34] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__children_repeat1, 2, 0, 0), SHIFT_REPEAT(93),
  [37] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__children_repeat1, 2, 0, 0), SHIFT_REPEAT(94),
  [40] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__children_repeat1, 2, 0, 0), SHIFT_REPEAT(85),
  [43] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__children_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [46] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [48] = {.entry = {.count = 1, .reusable = false}}, SHIFT(54),
  [50] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [52] = {.entry = {.count = 1, .reusable = false}}, SHIFT(61),
  [54] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [56] = {.entry = {.count = 1, .reusable = false}}, SHIFT(89),
  [58] = {.entry = {.count = 1, .reusable = false}}, SHIFT(95),
  [60] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [62] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [64] = {.entry = {.count = 1, .reusable = false}}, SHIFT(56),
  [66] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [68] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [70] = {.entry = {.count = 1, .reusable = false}}, SHIFT(93),
  [72] = {.entry = {.count = 1, .reusable = false}}, SHIFT(94),
  [74] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [76] = {.entry = {.count = 1, .reusable = false}}, SHIFT(52),
  [78] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [80] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [82] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [84] = {.entry = {.count = 1, .reusable = false}}, SHIFT(53),
  [86] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [88] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [94] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [97] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(89),
  [100] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(95),
  [103] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(91),
  [106] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(80),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [111] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag, 5, 0, 0),
  [115] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag, 5, 0, 0),
  [117] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag, 4, 0, 0),
  [121] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag, 4, 0, 0),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ruby_block_run, 3, 0, 0),
  [125] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_ruby_block_run, 3, 0, 0),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ruby_block_output, 3, 0, 0),
  [129] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_ruby_block_output, 3, 0, 0),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag, 3, 0, 0),
  [133] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag, 3, 0, 0),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag, 2, 0, 0),
  [137] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag, 2, 0, 0),
  [139] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_tag_repeat1, 2, 0, 0),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_tag_repeat1, 2, 0, 0),
  [143] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_tag_repeat1, 2, 0, 0), SHIFT_REPEAT(19),
  [146] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ruby_block_output, 4, 0, 0),
  [148] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_ruby_block_output, 4, 0, 0),
  [150] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [152] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag, 6, 0, 0),
  [154] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag, 6, 0, 0),
  [156] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__children, 3, 0, 0),
  [158] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__children, 3, 0, 0),
  [160] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ruby_block_run, 4, 0, 0),
  [162] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_ruby_block_run, 4, 0, 0),
  [164] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_text_content, 1, 0, 0),
  [166] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_text_content, 1, 0, 0),
  [168] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ruby_interpolation, 2, 0, 0),
  [170] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_ruby_interpolation, 2, 0, 0),
  [172] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_doctype, 3, 0, 0),
  [174] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_doctype, 3, 0, 0),
  [176] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_doctype, 2, 0, 0),
  [178] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_doctype, 2, 0, 0),
  [180] = {.entry = {.count = 1, .reusable = false}}, SHIFT(57),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [186] = {.entry = {.count = 1, .reusable = false}}, SHIFT(55),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [190] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [194] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [200] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_attributes, 1, 0, 0),
  [202] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attributes, 1, 0, 0),
  [204] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_html_attributes, 3, 0, 0),
  [206] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_html_attributes, 3, 0, 0),
  [208] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_html_attributes, 2, 0, 0),
  [210] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_html_attributes, 2, 0, 0),
  [212] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [214] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [216] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [218] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 1, 0, 0),
  [220] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_attribute, 1, 0, 0),
  [222] = {.entry = {.count = 1, .reusable = false}}, SHIFT(69),
  [224] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_html_attributes_repeat1, 2, 0, 0),
  [226] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_html_attributes_repeat1, 2, 0, 0), SHIFT_REPEAT(63),
  [229] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 3, 0, 0),
  [231] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_attribute, 3, 0, 0),
  [233] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_attribute_value, 3, 0, 0),
  [235] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_quoted_attribute_value, 3, 0, 0),
  [237] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [239] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_html_attributes_repeat1, 1, 0, 0),
  [241] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_attribute_value, 2, 0, 0),
  [243] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_quoted_attribute_value, 2, 0, 0),
  [245] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [247] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [249] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [251] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [253] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [255] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [257] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [259] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [261] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [263] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [265] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [267] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [269] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [271] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [273] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [275] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [277] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [279] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [281] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [283] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [285] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [287] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token__newline = 0,
  ts_external_token__indent = 1,
  ts_external_token__dedent = 2,
  ts_external_token_ruby_attributes = 3,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token__newline] = sym__newline,
  [ts_external_token__indent] = sym__indent,
  [ts_external_token__dedent] = sym__dedent,
  [ts_external_token_ruby_attributes] = sym_ruby_attributes,
};

static const bool ts_external_scanner_states[7][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token__newline] = true,
    [ts_external_token__indent] = true,
    [ts_external_token__dedent] = true,
    [ts_external_token_ruby_attributes] = true,
  },
  [2] = {
    [ts_external_token__newline] = true,
    [ts_external_token__dedent] = true,
  },
  [3] = {
    [ts_external_token__newline] = true,
    [ts_external_token_ruby_attributes] = true,
  },
  [4] = {
    [ts_external_token__newline] = true,
  },
  [5] = {
    [ts_external_token__newline] = true,
    [ts_external_token__indent] = true,
    [ts_external_token__dedent] = true,
  },
  [6] = {
    [ts_external_token__indent] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_haml_external_scanner_create(void);
void tree_sitter_haml_external_scanner_destroy(void *);
bool tree_sitter_haml_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_haml_external_scanner_serialize(void *, char *);
void tree_sitter_haml_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_haml(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_haml_external_scanner_create,
      tree_sitter_haml_external_scanner_destroy,
      tree_sitter_haml_external_scanner_scan,
      tree_sitter_haml_external_scanner_serialize,
      tree_sitter_haml_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
