#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 98
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 39
#define ALIAS_COUNT 0
#define TOKEN_COUNT 22
#define EXTERNAL_TOKEN_COUNT 4
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define PRODUCTION_ID_COUNT 1

enum ts_symbol_identifiers {
  anon_sym_SLASH = 1,
  anon_sym_SPACE = 2,
  anon_sym_LPAREN = 3,
  anon_sym_RPAREN = 4,
  sym_id = 5,
  sym_name = 6,
  sym_class = 7,
  sym_attribute_name = 8,
  anon_sym_EQ = 9,
  anon_sym_SQUOTE = 10,
  anon_sym_DQUOTE = 11,
  sym__text = 12,
  anon_sym_DASH = 13,
  anon_sym_POUND = 14,
  sym_ruby_expression = 15,
  sym__html_identifier = 16,
  anon_sym_BANG_BANG_BANG = 17,
  sym__newline = 18,
  sym__indent = 19,
  sym__dedent = 20,
  sym_ruby_attributes = 21,
  sym_source_file = 22,
  sym_tag = 23,
  sym__children = 24,
  sym__children_choice = 25,
  sym_html_attributes = 26,
  sym_attributes = 27,
  sym_attribute = 28,
  sym_quoted_attribute_value = 29,
  sym_text_content = 30,
  sym_ruby_block_output = 31,
  sym_ruby_block_run = 32,
  sym_ruby_interpolation = 33,
  sym_doctype = 34,
  aux_sym_source_file_repeat1 = 35,
  aux_sym_tag_repeat1 = 36,
  aux_sym__children_repeat1 = 37,
  aux_sym_html_attributes_repeat1 = 38,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_SLASH] = "self_close_slash",
  [anon_sym_SPACE] = " ",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [sym_id] = "id",
  [sym_name] = "name",
  [sym_class] = "class",
  [sym_attribute_name] = "attribute_name",
  [anon_sym_EQ] = "=",
  [anon_sym_SQUOTE] = "'",
  [anon_sym_DQUOTE] = "\"",
  [sym__text] = "_text",
  [anon_sym_DASH] = "-",
  [anon_sym_POUND] = "#",
  [sym_ruby_expression] = "ruby_expression",
  [sym__html_identifier] = "attribute_value",
  [anon_sym_BANG_BANG_BANG] = "!!!",
  [sym__newline] = "_newline",
  [sym__indent] = "_indent",
  [sym__dedent] = "_dedent",
  [sym_ruby_attributes] = "ruby_attributes",
  [sym_source_file] = "source_file",
  [sym_tag] = "tag",
  [sym__children] = "_children",
  [sym__children_choice] = "_children_choice",
  [sym_html_attributes] = "html_attributes",
  [sym_attributes] = "attributes",
  [sym_attribute] = "attribute",
  [sym_quoted_attribute_value] = "quoted_attribute_value",
  [sym_text_content] = "text_content",
  [sym_ruby_block_output] = "ruby_block_output",
  [sym_ruby_block_run] = "ruby_block_run",
  [sym_ruby_interpolation] = "ruby_interpolation",
  [sym_doctype] = "doctype",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_tag_repeat1] = "tag_repeat1",
  [aux_sym__children_repeat1] = "_children_repeat1",
  [aux_sym_html_attributes_repeat1] = "html_attributes_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_SPACE] = anon_sym_SPACE,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [sym_id] = sym_id,
  [sym_name] = sym_name,
  [sym_class] = sym_class,
  [sym_attribute_name] = sym_attribute_name,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [sym__text] = sym__text,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_POUND] = anon_sym_POUND,
  [sym_ruby_expression] = sym_ruby_expression,
  [sym__html_identifier] = sym__html_identifier,
  [anon_sym_BANG_BANG_BANG] = anon_sym_BANG_BANG_BANG,
  [sym__newline] = sym__newline,
  [sym__indent] = sym__indent,
  [sym__dedent] = sym__dedent,
  [sym_ruby_attributes] = sym_ruby_attributes,
  [sym_source_file] = sym_source_file,
  [sym_tag] = sym_tag,
  [sym__children] = sym__children,
  [sym__children_choice] = sym__children_choice,
  [sym_html_attributes] = sym_html_attributes,
  [sym_attributes] = sym_attributes,
  [sym_attribute] = sym_attribute,
  [sym_quoted_attribute_value] = sym_quoted_attribute_value,
  [sym_text_content] = sym_text_content,
  [sym_ruby_block_output] = sym_ruby_block_output,
  [sym_ruby_block_run] = sym_ruby_block_run,
  [sym_ruby_interpolation] = sym_ruby_interpolation,
  [sym_doctype] = sym_doctype,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_tag_repeat1] = aux_sym_tag_repeat1,
  [aux_sym__children_repeat1] = aux_sym__children_repeat1,
  [aux_sym_html_attributes_repeat1] = aux_sym_html_attributes_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SPACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [sym_id] = {
    .visible = true,
    .named = true,
  },
  [sym_name] = {
    .visible = true,
    .named = true,
  },
  [sym_class] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute_name] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [sym__text] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [sym_ruby_expression] = {
    .visible = true,
    .named = true,
  },
  [sym__html_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_BANG_BANG_BANG] = {
    .visible = true,
    .named = false,
  },
  [sym__newline] = {
    .visible = false,
    .named = true,
  },
  [sym__indent] = {
    .visible = false,
    .named = true,
  },
  [sym__dedent] = {
    .visible = false,
    .named = true,
  },
  [sym_ruby_attributes] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_tag] = {
    .visible = true,
    .named = true,
  },
  [sym__children] = {
    .visible = false,
    .named = true,
  },
  [sym__children_choice] = {
    .visible = false,
    .named = true,
  },
  [sym_html_attributes] = {
    .visible = true,
    .named = true,
  },
  [sym_attributes] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym_quoted_attribute_value] = {
    .visible = true,
    .named = true,
  },
  [sym_text_content] = {
    .visible = true,
    .named = true,
  },
  [sym_ruby_block_output] = {
    .visible = true,
    .named = true,
  },
  [sym_ruby_block_run] = {
    .visible = true,
    .named = true,
  },
  [sym_ruby_interpolation] = {
    .visible = true,
    .named = true,
  },
  [sym_doctype] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_tag_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__children_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_html_attributes_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 2,
  [6] = 6,
  [7] = 4,
  [8] = 3,
  [9] = 9,
  [10] = 9,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 16,
  [24] = 24,
  [25] = 19,
  [26] = 26,
  [27] = 27,
  [28] = 20,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 18,
  [35] = 21,
  [36] = 15,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 30,
  [41] = 41,
  [42] = 26,
  [43] = 31,
  [44] = 27,
  [45] = 29,
  [46] = 46,
  [47] = 38,
  [48] = 37,
  [49] = 24,
  [50] = 22,
  [51] = 33,
  [52] = 32,
  [53] = 39,
  [54] = 54,
  [55] = 54,
  [56] = 56,
  [57] = 57,
  [58] = 57,
  [59] = 56,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 74,
  [76] = 76,
  [77] = 76,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 80,
  [83] = 81,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 88,
  [91] = 91,
  [92] = 92,
  [93] = 85,
  [94] = 89,
  [95] = 92,
  [96] = 96,
  [97] = 96,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(13);
      ADVANCE_MAP(
        '!', 5,
        '"', 24,
        '#', 28,
        '%', 11,
        '\'', 23,
        '(', 16,
        ')', 17,
        '-', 27,
        '.', 9,
        '/', 14,
        '=', 22,
        '{', 8,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == '\n') SKIP(1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(25);
      if (lookahead != 0) ADVANCE(26);
      END_STATE();
    case 2:
      ADVANCE_MAP(
        ' ', 15,
        '#', 10,
        '%', 11,
        '(', 16,
        '-', 27,
        '.', 9,
        '/', 14,
        '=', 22,
      );
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(2);
      END_STATE();
    case 3:
      if (lookahead == ' ') ADVANCE(15);
      if (lookahead == '#') ADVANCE(12);
      if (lookahead == ')') ADVANCE(17);
      if (lookahead == '=') ADVANCE(22);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(3);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 4:
      if (lookahead == '!') ADVANCE(31);
      END_STATE();
    case 5:
      if (lookahead == '!') ADVANCE(4);
      END_STATE();
    case 6:
      if (lookahead == '"') ADVANCE(24);
      if (lookahead == '\'') ADVANCE(23);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(6);
      if (('-' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(30);
      END_STATE();
    case 7:
      if (lookahead == '#') ADVANCE(12);
      if (lookahead == ')') ADVANCE(17);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(7);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 8:
      if (lookahead == '}') ADVANCE(29);
      if (lookahead != 0) ADVANCE(8);
      END_STATE();
    case 9:
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9')) ADVANCE(9);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 10:
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(18);
      END_STATE();
    case 11:
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(19);
      END_STATE();
    case 12:
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_SPACE);
      if (lookahead == ' ') ADVANCE(15);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_id);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(18);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(19);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_class);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9')) ADVANCE(20);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_attribute_name);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym__text);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(25);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(26);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym__text);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(26);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_POUND);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(18);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_ruby_expression);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym__html_identifier);
      if (('-' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(30);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_BANG_BANG_BANG);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 2, .external_lex_state = 2},
  [3] = {.lex_state = 0, .external_lex_state = 3},
  [4] = {.lex_state = 2, .external_lex_state = 2},
  [5] = {.lex_state = 2, .external_lex_state = 2},
  [6] = {.lex_state = 0, .external_lex_state = 3},
  [7] = {.lex_state = 2, .external_lex_state = 2},
  [8] = {.lex_state = 0, .external_lex_state = 3},
  [9] = {.lex_state = 0, .external_lex_state = 4},
  [10] = {.lex_state = 0, .external_lex_state = 4},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0, .external_lex_state = 5},
  [16] = {.lex_state = 0, .external_lex_state = 5},
  [17] = {.lex_state = 2, .external_lex_state = 2},
  [18] = {.lex_state = 0, .external_lex_state = 5},
  [19] = {.lex_state = 0, .external_lex_state = 5},
  [20] = {.lex_state = 0, .external_lex_state = 5},
  [21] = {.lex_state = 0, .external_lex_state = 5},
  [22] = {.lex_state = 0, .external_lex_state = 3},
  [23] = {.lex_state = 0, .external_lex_state = 6},
  [24] = {.lex_state = 0, .external_lex_state = 3},
  [25] = {.lex_state = 0, .external_lex_state = 6},
  [26] = {.lex_state = 0, .external_lex_state = 3},
  [27] = {.lex_state = 0, .external_lex_state = 3},
  [28] = {.lex_state = 0, .external_lex_state = 6},
  [29] = {.lex_state = 0, .external_lex_state = 3},
  [30] = {.lex_state = 0, .external_lex_state = 3},
  [31] = {.lex_state = 0, .external_lex_state = 3},
  [32] = {.lex_state = 0, .external_lex_state = 3},
  [33] = {.lex_state = 0, .external_lex_state = 3},
  [34] = {.lex_state = 0, .external_lex_state = 6},
  [35] = {.lex_state = 0, .external_lex_state = 6},
  [36] = {.lex_state = 0, .external_lex_state = 6},
  [37] = {.lex_state = 0, .external_lex_state = 3},
  [38] = {.lex_state = 2, .external_lex_state = 4},
  [39] = {.lex_state = 2, .external_lex_state = 4},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 2, .external_lex_state = 4},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 2, .external_lex_state = 4},
  [54] = {.lex_state = 2, .external_lex_state = 4},
  [55] = {.lex_state = 2, .external_lex_state = 4},
  [56] = {.lex_state = 2, .external_lex_state = 4},
  [57] = {.lex_state = 2, .external_lex_state = 4},
  [58] = {.lex_state = 2, .external_lex_state = 4},
  [59] = {.lex_state = 2, .external_lex_state = 4},
  [60] = {.lex_state = 2, .external_lex_state = 4},
  [61] = {.lex_state = 2, .external_lex_state = 4},
  [62] = {.lex_state = 2, .external_lex_state = 4},
  [63] = {.lex_state = 7},
  [64] = {.lex_state = 7},
  [65] = {.lex_state = 7},
  [66] = {.lex_state = 3},
  [67] = {.lex_state = 3},
  [68] = {.lex_state = 3},
  [69] = {.lex_state = 3},
  [70] = {.lex_state = 3},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 6},
  [73] = {.lex_state = 6},
  [74] = {.lex_state = 1},
  [75] = {.lex_state = 1},
  [76] = {.lex_state = 1},
  [77] = {.lex_state = 1},
  [78] = {.lex_state = 7},
  [79] = {.lex_state = 1, .external_lex_state = 4},
  [80] = {.lex_state = 1},
  [81] = {.lex_state = 1},
  [82] = {.lex_state = 1},
  [83] = {.lex_state = 1},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0, .external_lex_state = 4},
  [89] = {.lex_state = 0, .external_lex_state = 4},
  [90] = {.lex_state = 0, .external_lex_state = 4},
  [91] = {.lex_state = 0, .external_lex_state = 4},
  [92] = {.lex_state = 1},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0, .external_lex_state = 4},
  [95] = {.lex_state = 1},
  [96] = {.lex_state = 1},
  [97] = {.lex_state = 1},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [sym_id] = ACTIONS(1),
    [sym_name] = ACTIONS(1),
    [sym_class] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(1),
    [sym_ruby_expression] = ACTIONS(1),
    [anon_sym_BANG_BANG_BANG] = ACTIONS(1),
    [sym__newline] = ACTIONS(1),
    [sym__indent] = ACTIONS(1),
    [sym__dedent] = ACTIONS(1),
    [sym_ruby_attributes] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(86),
    [sym_tag] = STATE(13),
    [sym_ruby_block_output] = STATE(13),
    [sym_ruby_block_run] = STATE(13),
    [sym_ruby_interpolation] = STATE(13),
    [sym_doctype] = STATE(12),
    [aux_sym_source_file_repeat1] = STATE(13),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_id] = ACTIONS(5),
    [sym_name] = ACTIONS(5),
    [sym_class] = ACTIONS(5),
    [anon_sym_EQ] = ACTIONS(7),
    [anon_sym_DASH] = ACTIONS(9),
    [anon_sym_POUND] = ACTIONS(11),
    [anon_sym_BANG_BANG_BANG] = ACTIONS(13),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 12,
    ACTIONS(15), 1,
      anon_sym_SLASH,
    ACTIONS(17), 1,
      anon_sym_SPACE,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(23), 1,
      anon_sym_EQ,
    ACTIONS(25), 1,
      anon_sym_DASH,
    ACTIONS(27), 1,
      sym__newline,
    ACTIONS(29), 1,
      sym_ruby_attributes,
    STATE(7), 1,
      aux_sym_tag_repeat1,
    STATE(39), 1,
      sym_attributes,
    STATE(62), 1,
      sym_html_attributes,
    STATE(52), 2,
      sym_ruby_block_output,
      sym_ruby_block_run,
    ACTIONS(21), 3,
      sym_id,
      sym_name,
      sym_class,
  [40] = 8,
    ACTIONS(31), 1,
      ts_builtin_sym_end,
    ACTIONS(35), 1,
      anon_sym_EQ,
    ACTIONS(37), 1,
      anon_sym_DASH,
    ACTIONS(39), 1,
      anon_sym_POUND,
    ACTIONS(41), 1,
      sym__newline,
    ACTIONS(43), 1,
      sym__dedent,
    ACTIONS(33), 3,
      sym_id,
      sym_name,
      sym_class,
    STATE(6), 6,
      sym_tag,
      sym__children_choice,
      sym_ruby_block_output,
      sym_ruby_block_run,
      sym_ruby_interpolation,
      aux_sym__children_repeat1,
  [72] = 12,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(29), 1,
      sym_ruby_attributes,
    ACTIONS(45), 1,
      anon_sym_SLASH,
    ACTIONS(47), 1,
      anon_sym_SPACE,
    ACTIONS(51), 1,
      anon_sym_EQ,
    ACTIONS(53), 1,
      anon_sym_DASH,
    ACTIONS(55), 1,
      sym__newline,
    STATE(17), 1,
      aux_sym_tag_repeat1,
    STATE(47), 1,
      sym_attributes,
    STATE(62), 1,
      sym_html_attributes,
    STATE(30), 2,
      sym_ruby_block_output,
      sym_ruby_block_run,
    ACTIONS(49), 3,
      sym_id,
      sym_name,
      sym_class,
  [112] = 12,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(29), 1,
      sym_ruby_attributes,
    ACTIONS(51), 1,
      anon_sym_EQ,
    ACTIONS(53), 1,
      anon_sym_DASH,
    ACTIONS(57), 1,
      anon_sym_SLASH,
    ACTIONS(59), 1,
      anon_sym_SPACE,
    ACTIONS(63), 1,
      sym__newline,
    STATE(4), 1,
      aux_sym_tag_repeat1,
    STATE(53), 1,
      sym_attributes,
    STATE(62), 1,
      sym_html_attributes,
    STATE(32), 2,
      sym_ruby_block_output,
      sym_ruby_block_run,
    ACTIONS(61), 3,
      sym_id,
      sym_name,
      sym_class,
  [152] = 7,
    ACTIONS(70), 1,
      anon_sym_EQ,
    ACTIONS(73), 1,
      anon_sym_DASH,
    ACTIONS(76), 1,
      anon_sym_POUND,
    ACTIONS(79), 1,
      sym__newline,
    ACTIONS(65), 2,
      sym__dedent,
      ts_builtin_sym_end,
    ACTIONS(67), 3,
      sym_id,
      sym_name,
      sym_class,
    STATE(6), 6,
      sym_tag,
      sym__children_choice,
      sym_ruby_block_output,
      sym_ruby_block_run,
      sym_ruby_interpolation,
      aux_sym__children_repeat1,
  [182] = 12,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(23), 1,
      anon_sym_EQ,
    ACTIONS(25), 1,
      anon_sym_DASH,
    ACTIONS(29), 1,
      sym_ruby_attributes,
    ACTIONS(82), 1,
      anon_sym_SLASH,
    ACTIONS(84), 1,
      anon_sym_SPACE,
    ACTIONS(86), 1,
      sym__newline,
    STATE(17), 1,
      aux_sym_tag_repeat1,
    STATE(38), 1,
      sym_attributes,
    STATE(62), 1,
      sym_html_attributes,
    STATE(40), 2,
      sym_ruby_block_output,
      sym_ruby_block_run,
    ACTIONS(49), 3,
      sym_id,
      sym_name,
      sym_class,
  [222] = 8,
    ACTIONS(31), 1,
      ts_builtin_sym_end,
    ACTIONS(35), 1,
      anon_sym_EQ,
    ACTIONS(37), 1,
      anon_sym_DASH,
    ACTIONS(39), 1,
      anon_sym_POUND,
    ACTIONS(41), 1,
      sym__newline,
    ACTIONS(88), 1,
      sym__dedent,
    ACTIONS(33), 3,
      sym_id,
      sym_name,
      sym_class,
    STATE(6), 6,
      sym_tag,
      sym__children_choice,
      sym_ruby_block_output,
      sym_ruby_block_run,
      sym_ruby_interpolation,
      aux_sym__children_repeat1,
  [254] = 6,
    ACTIONS(35), 1,
      anon_sym_EQ,
    ACTIONS(37), 1,
      anon_sym_DASH,
    ACTIONS(39), 1,
      anon_sym_POUND,
    ACTIONS(90), 1,
      sym__newline,
    ACTIONS(33), 3,
      sym_id,
      sym_name,
      sym_class,
    STATE(3), 6,
      sym_tag,
      sym__children_choice,
      sym_ruby_block_output,
      sym_ruby_block_run,
      sym_ruby_interpolation,
      aux_sym__children_repeat1,
  [280] = 6,
    ACTIONS(35), 1,
      anon_sym_EQ,
    ACTIONS(37), 1,
      anon_sym_DASH,
    ACTIONS(39), 1,
      anon_sym_POUND,
    ACTIONS(92), 1,
      sym__newline,
    ACTIONS(33), 3,
      sym_id,
      sym_name,
      sym_class,
    STATE(8), 6,
      sym_tag,
      sym__children_choice,
      sym_ruby_block_output,
      sym_ruby_block_run,
      sym_ruby_interpolation,
      aux_sym__children_repeat1,
  [306] = 6,
    ACTIONS(94), 1,
      ts_builtin_sym_end,
    ACTIONS(99), 1,
      anon_sym_EQ,
    ACTIONS(102), 1,
      anon_sym_DASH,
    ACTIONS(105), 1,
      anon_sym_POUND,
    ACTIONS(96), 3,
      sym_id,
      sym_name,
      sym_class,
    STATE(11), 5,
      sym_tag,
      sym_ruby_block_output,
      sym_ruby_block_run,
      sym_ruby_interpolation,
      aux_sym_source_file_repeat1,
  [331] = 6,
    ACTIONS(7), 1,
      anon_sym_EQ,
    ACTIONS(9), 1,
      anon_sym_DASH,
    ACTIONS(11), 1,
      anon_sym_POUND,
    ACTIONS(108), 1,
      ts_builtin_sym_end,
    ACTIONS(5), 3,
      sym_id,
      sym_name,
      sym_class,
    STATE(14), 5,
      sym_tag,
      sym_ruby_block_output,
      sym_ruby_block_run,
      sym_ruby_interpolation,
      aux_sym_source_file_repeat1,
  [356] = 6,
    ACTIONS(7), 1,
      anon_sym_EQ,
    ACTIONS(9), 1,
      anon_sym_DASH,
    ACTIONS(11), 1,
      anon_sym_POUND,
    ACTIONS(108), 1,
      ts_builtin_sym_end,
    ACTIONS(5), 3,
      sym_id,
      sym_name,
      sym_class,
    STATE(11), 5,
      sym_tag,
      sym_ruby_block_output,
      sym_ruby_block_run,
      sym_ruby_interpolation,
      aux_sym_source_file_repeat1,
  [381] = 6,
    ACTIONS(7), 1,
      anon_sym_EQ,
    ACTIONS(9), 1,
      anon_sym_DASH,
    ACTIONS(11), 1,
      anon_sym_POUND,
    ACTIONS(110), 1,
      ts_builtin_sym_end,
    ACTIONS(5), 3,
      sym_id,
      sym_name,
      sym_class,
    STATE(11), 5,
      sym_tag,
      sym_ruby_block_output,
      sym_ruby_block_run,
      sym_ruby_interpolation,
      aux_sym_source_file_repeat1,
  [406] = 4,
    ACTIONS(114), 1,
      anon_sym_POUND,
    ACTIONS(116), 1,
      sym__indent,
    STATE(37), 1,
      sym__children,
    ACTIONS(112), 8,
      sym__newline,
      sym__dedent,
      ts_builtin_sym_end,
      sym_id,
      sym_name,
      sym_class,
      anon_sym_EQ,
      anon_sym_DASH,
  [426] = 4,
    ACTIONS(116), 1,
      sym__indent,
    ACTIONS(120), 1,
      anon_sym_POUND,
    STATE(24), 1,
      sym__children,
    ACTIONS(118), 8,
      sym__newline,
      sym__dedent,
      ts_builtin_sym_end,
      sym_id,
      sym_name,
      sym_class,
      anon_sym_EQ,
      anon_sym_DASH,
  [446] = 4,
    STATE(17), 1,
      aux_sym_tag_repeat1,
    ACTIONS(124), 3,
      sym__newline,
      sym_ruby_attributes,
      anon_sym_SPACE,
    ACTIONS(126), 3,
      sym_id,
      sym_name,
      sym_class,
    ACTIONS(122), 4,
      anon_sym_SLASH,
      anon_sym_LPAREN,
      anon_sym_EQ,
      anon_sym_DASH,
  [466] = 4,
    ACTIONS(116), 1,
      sym__indent,
    ACTIONS(131), 1,
      anon_sym_POUND,
    STATE(29), 1,
      sym__children,
    ACTIONS(129), 8,
      sym__newline,
      sym__dedent,
      ts_builtin_sym_end,
      sym_id,
      sym_name,
      sym_class,
      anon_sym_EQ,
      anon_sym_DASH,
  [486] = 4,
    ACTIONS(116), 1,
      sym__indent,
    ACTIONS(135), 1,
      anon_sym_POUND,
    STATE(30), 1,
      sym__children,
    ACTIONS(133), 8,
      sym__newline,
      sym__dedent,
      ts_builtin_sym_end,
      sym_id,
      sym_name,
      sym_class,
      anon_sym_EQ,
      anon_sym_DASH,
  [506] = 4,
    ACTIONS(116), 1,
      sym__indent,
    ACTIONS(139), 1,
      anon_sym_POUND,
    STATE(26), 1,
      sym__children,
    ACTIONS(137), 8,
      sym__newline,
      sym__dedent,
      ts_builtin_sym_end,
      sym_id,
      sym_name,
      sym_class,
      anon_sym_EQ,
      anon_sym_DASH,
  [526] = 4,
    ACTIONS(116), 1,
      sym__indent,
    ACTIONS(143), 1,
      anon_sym_POUND,
    STATE(22), 1,
      sym__children,
    ACTIONS(141), 8,
      sym__newline,
      sym__dedent,
      ts_builtin_sym_end,
      sym_id,
      sym_name,
      sym_class,
      anon_sym_EQ,
      anon_sym_DASH,
  [546] = 2,
    ACTIONS(147), 1,
      anon_sym_POUND,
    ACTIONS(145), 8,
      sym__newline,
      sym__dedent,
      ts_builtin_sym_end,
      sym_id,
      sym_name,
      sym_class,
      anon_sym_EQ,
      anon_sym_DASH,
  [560] = 4,
    ACTIONS(120), 1,
      anon_sym_POUND,
    ACTIONS(149), 1,
      sym__indent,
    STATE(49), 1,
      sym__children,
    ACTIONS(118), 6,
      ts_builtin_sym_end,
      sym_id,
      sym_name,
      sym_class,
      anon_sym_EQ,
      anon_sym_DASH,
  [578] = 2,
    ACTIONS(153), 1,
      anon_sym_POUND,
    ACTIONS(151), 8,
      sym__newline,
      sym__dedent,
      ts_builtin_sym_end,
      sym_id,
      sym_name,
      sym_class,
      anon_sym_EQ,
      anon_sym_DASH,
  [592] = 4,
    ACTIONS(135), 1,
      anon_sym_POUND,
    ACTIONS(149), 1,
      sym__indent,
    STATE(40), 1,
      sym__children,
    ACTIONS(133), 6,
      ts_builtin_sym_end,
      sym_id,
      sym_name,
      sym_class,
      anon_sym_EQ,
      anon_sym_DASH,
  [610] = 2,
    ACTIONS(114), 1,
      anon_sym_POUND,
    ACTIONS(112), 8,
      sym__newline,
      sym__dedent,
      ts_builtin_sym_end,
      sym_id,
      sym_name,
      sym_class,
      anon_sym_EQ,
      anon_sym_DASH,
  [624] = 2,
    ACTIONS(157), 1,
      anon_sym_POUND,
    ACTIONS(155), 8,
      sym__newline,
      sym__dedent,
      ts_builtin_sym_end,
      sym_id,
      sym_name,
      sym_class,
      anon_sym_EQ,
      anon_sym_DASH,
  [638] = 4,
    ACTIONS(139), 1,
      anon_sym_POUND,
    ACTIONS(149), 1,
      sym__indent,
    STATE(42), 1,
      sym__children,
    ACTIONS(137), 6,
      ts_builtin_sym_end,
      sym_id,
      sym_name,
      sym_class,
      anon_sym_EQ,
      anon_sym_DASH,
  [656] = 2,
    ACTIONS(161), 1,
      anon_sym_POUND,
    ACTIONS(159), 8,
      sym__newline,
      sym__dedent,
      ts_builtin_sym_end,
      sym_id,
      sym_name,
      sym_class,
      anon_sym_EQ,
      anon_sym_DASH,
  [670] = 2,
    ACTIONS(139), 1,
      anon_sym_POUND,
    ACTIONS(137), 8,
      sym__newline,
      sym__dedent,
      ts_builtin_sym_end,
      sym_id,
      sym_name,
      sym_class,
      anon_sym_EQ,
      anon_sym_DASH,
  [684] = 2,
    ACTIONS(165), 1,
      anon_sym_POUND,
    ACTIONS(163), 8,
      sym__newline,
      sym__dedent,
      ts_builtin_sym_end,
      sym_id,
      sym_name,
      sym_class,
      anon_sym_EQ,
      anon_sym_DASH,
  [698] = 2,
    ACTIONS(135), 1,
      anon_sym_POUND,
    ACTIONS(133), 8,
      sym__newline,
      sym__dedent,
      ts_builtin_sym_end,
      sym_id,
      sym_name,
      sym_class,
      anon_sym_EQ,
      anon_sym_DASH,
  [712] = 2,
    ACTIONS(169), 1,
      anon_sym_POUND,
    ACTIONS(167), 8,
      sym__newline,
      sym__dedent,
      ts_builtin_sym_end,
      sym_id,
      sym_name,
      sym_class,
      anon_sym_EQ,
      anon_sym_DASH,
  [726] = 4,
    ACTIONS(131), 1,
      anon_sym_POUND,
    ACTIONS(149), 1,
      sym__indent,
    STATE(45), 1,
      sym__children,
    ACTIONS(129), 6,
      ts_builtin_sym_end,
      sym_id,
      sym_name,
      sym_class,
      anon_sym_EQ,
      anon_sym_DASH,
  [744] = 4,
    ACTIONS(143), 1,
      anon_sym_POUND,
    ACTIONS(149), 1,
      sym__indent,
    STATE(50), 1,
      sym__children,
    ACTIONS(141), 6,
      ts_builtin_sym_end,
      sym_id,
      sym_name,
      sym_class,
      anon_sym_EQ,
      anon_sym_DASH,
  [762] = 4,
    ACTIONS(114), 1,
      anon_sym_POUND,
    ACTIONS(149), 1,
      sym__indent,
    STATE(48), 1,
      sym__children,
    ACTIONS(112), 6,
      ts_builtin_sym_end,
      sym_id,
      sym_name,
      sym_class,
      anon_sym_EQ,
      anon_sym_DASH,
  [780] = 2,
    ACTIONS(131), 1,
      anon_sym_POUND,
    ACTIONS(129), 8,
      sym__newline,
      sym__dedent,
      ts_builtin_sym_end,
      sym_id,
      sym_name,
      sym_class,
      anon_sym_EQ,
      anon_sym_DASH,
  [794] = 6,
    ACTIONS(23), 1,
      anon_sym_EQ,
    ACTIONS(25), 1,
      anon_sym_DASH,
    ACTIONS(171), 1,
      anon_sym_SLASH,
    ACTIONS(173), 1,
      anon_sym_SPACE,
    ACTIONS(175), 1,
      sym__newline,
    STATE(42), 2,
      sym_ruby_block_output,
      sym_ruby_block_run,
  [814] = 6,
    ACTIONS(23), 1,
      anon_sym_EQ,
    ACTIONS(25), 1,
      anon_sym_DASH,
    ACTIONS(82), 1,
      anon_sym_SLASH,
    ACTIONS(84), 1,
      anon_sym_SPACE,
    ACTIONS(86), 1,
      sym__newline,
    STATE(40), 2,
      sym_ruby_block_output,
      sym_ruby_block_run,
  [834] = 2,
    ACTIONS(139), 1,
      anon_sym_POUND,
    ACTIONS(137), 6,
      ts_builtin_sym_end,
      sym_id,
      sym_name,
      sym_class,
      anon_sym_EQ,
      anon_sym_DASH,
  [846] = 2,
    ACTIONS(179), 1,
      anon_sym_POUND,
    ACTIONS(177), 6,
      ts_builtin_sym_end,
      sym_id,
      sym_name,
      sym_class,
      anon_sym_EQ,
      anon_sym_DASH,
  [858] = 2,
    ACTIONS(114), 1,
      anon_sym_POUND,
    ACTIONS(112), 6,
      ts_builtin_sym_end,
      sym_id,
      sym_name,
      sym_class,
      anon_sym_EQ,
      anon_sym_DASH,
  [870] = 2,
    ACTIONS(165), 1,
      anon_sym_POUND,
    ACTIONS(163), 6,
      ts_builtin_sym_end,
      sym_id,
      sym_name,
      sym_class,
      anon_sym_EQ,
      anon_sym_DASH,
  [882] = 2,
    ACTIONS(157), 1,
      anon_sym_POUND,
    ACTIONS(155), 6,
      ts_builtin_sym_end,
      sym_id,
      sym_name,
      sym_class,
      anon_sym_EQ,
      anon_sym_DASH,
  [894] = 2,
    ACTIONS(161), 1,
      anon_sym_POUND,
    ACTIONS(159), 6,
      ts_builtin_sym_end,
      sym_id,
      sym_name,
      sym_class,
      anon_sym_EQ,
      anon_sym_DASH,
  [906] = 2,
    ACTIONS(183), 1,
      anon_sym_POUND,
    ACTIONS(181), 6,
      ts_builtin_sym_end,
      sym_id,
      sym_name,
      sym_class,
      anon_sym_EQ,
      anon_sym_DASH,
  [918] = 6,
    ACTIONS(51), 1,
      anon_sym_EQ,
    ACTIONS(53), 1,
      anon_sym_DASH,
    ACTIONS(185), 1,
      anon_sym_SLASH,
    ACTIONS(187), 1,
      anon_sym_SPACE,
    ACTIONS(189), 1,
      sym__newline,
    STATE(26), 2,
      sym_ruby_block_output,
      sym_ruby_block_run,
  [938] = 2,
    ACTIONS(131), 1,
      anon_sym_POUND,
    ACTIONS(129), 6,
      ts_builtin_sym_end,
      sym_id,
      sym_name,
      sym_class,
      anon_sym_EQ,
      anon_sym_DASH,
  [950] = 2,
    ACTIONS(153), 1,
      anon_sym_POUND,
    ACTIONS(151), 6,
      ts_builtin_sym_end,
      sym_id,
      sym_name,
      sym_class,
      anon_sym_EQ,
      anon_sym_DASH,
  [962] = 2,
    ACTIONS(147), 1,
      anon_sym_POUND,
    ACTIONS(145), 6,
      ts_builtin_sym_end,
      sym_id,
      sym_name,
      sym_class,
      anon_sym_EQ,
      anon_sym_DASH,
  [974] = 2,
    ACTIONS(169), 1,
      anon_sym_POUND,
    ACTIONS(167), 6,
      ts_builtin_sym_end,
      sym_id,
      sym_name,
      sym_class,
      anon_sym_EQ,
      anon_sym_DASH,
  [986] = 2,
    ACTIONS(135), 1,
      anon_sym_POUND,
    ACTIONS(133), 6,
      ts_builtin_sym_end,
      sym_id,
      sym_name,
      sym_class,
      anon_sym_EQ,
      anon_sym_DASH,
  [998] = 6,
    ACTIONS(45), 1,
      anon_sym_SLASH,
    ACTIONS(47), 1,
      anon_sym_SPACE,
    ACTIONS(51), 1,
      anon_sym_EQ,
    ACTIONS(53), 1,
      anon_sym_DASH,
    ACTIONS(55), 1,
      sym__newline,
    STATE(30), 2,
      sym_ruby_block_output,
      sym_ruby_block_run,
  [1018] = 5,
    ACTIONS(23), 1,
      anon_sym_EQ,
    ACTIONS(25), 1,
      anon_sym_DASH,
    ACTIONS(173), 1,
      anon_sym_SPACE,
    ACTIONS(175), 1,
      sym__newline,
    STATE(42), 2,
      sym_ruby_block_output,
      sym_ruby_block_run,
  [1035] = 5,
    ACTIONS(51), 1,
      anon_sym_EQ,
    ACTIONS(53), 1,
      anon_sym_DASH,
    ACTIONS(187), 1,
      anon_sym_SPACE,
    ACTIONS(189), 1,
      sym__newline,
    STATE(26), 2,
      sym_ruby_block_output,
      sym_ruby_block_run,
  [1052] = 5,
    ACTIONS(23), 1,
      anon_sym_EQ,
    ACTIONS(25), 1,
      anon_sym_DASH,
    ACTIONS(191), 1,
      anon_sym_SPACE,
    ACTIONS(193), 1,
      sym__newline,
    STATE(48), 2,
      sym_ruby_block_output,
      sym_ruby_block_run,
  [1069] = 5,
    ACTIONS(23), 1,
      anon_sym_EQ,
    ACTIONS(25), 1,
      anon_sym_DASH,
    ACTIONS(84), 1,
      anon_sym_SPACE,
    ACTIONS(86), 1,
      sym__newline,
    STATE(40), 2,
      sym_ruby_block_output,
      sym_ruby_block_run,
  [1086] = 5,
    ACTIONS(47), 1,
      anon_sym_SPACE,
    ACTIONS(51), 1,
      anon_sym_EQ,
    ACTIONS(53), 1,
      anon_sym_DASH,
    ACTIONS(55), 1,
      sym__newline,
    STATE(30), 2,
      sym_ruby_block_output,
      sym_ruby_block_run,
  [1103] = 5,
    ACTIONS(51), 1,
      anon_sym_EQ,
    ACTIONS(53), 1,
      anon_sym_DASH,
    ACTIONS(195), 1,
      anon_sym_SPACE,
    ACTIONS(197), 1,
      sym__newline,
    STATE(37), 2,
      sym_ruby_block_output,
      sym_ruby_block_run,
  [1120] = 2,
    ACTIONS(201), 2,
      sym__newline,
      anon_sym_SPACE,
    ACTIONS(199), 3,
      anon_sym_SLASH,
      anon_sym_EQ,
      anon_sym_DASH,
  [1130] = 2,
    ACTIONS(205), 2,
      sym__newline,
      anon_sym_SPACE,
    ACTIONS(203), 3,
      anon_sym_SLASH,
      anon_sym_EQ,
      anon_sym_DASH,
  [1140] = 2,
    ACTIONS(209), 2,
      sym__newline,
      anon_sym_SPACE,
    ACTIONS(207), 3,
      anon_sym_SLASH,
      anon_sym_EQ,
      anon_sym_DASH,
  [1150] = 4,
    ACTIONS(211), 1,
      anon_sym_RPAREN,
    ACTIONS(213), 1,
      sym_attribute_name,
    STATE(65), 1,
      aux_sym_html_attributes_repeat1,
    STATE(68), 1,
      sym_attribute,
  [1163] = 4,
    ACTIONS(215), 1,
      anon_sym_RPAREN,
    ACTIONS(217), 1,
      sym_attribute_name,
    STATE(64), 1,
      aux_sym_html_attributes_repeat1,
    STATE(68), 1,
      sym_attribute,
  [1176] = 4,
    ACTIONS(213), 1,
      sym_attribute_name,
    ACTIONS(220), 1,
      anon_sym_RPAREN,
    STATE(64), 1,
      aux_sym_html_attributes_repeat1,
    STATE(68), 1,
      sym_attribute,
  [1189] = 3,
    ACTIONS(222), 1,
      anon_sym_SPACE,
    ACTIONS(226), 1,
      anon_sym_EQ,
    ACTIONS(224), 2,
      anon_sym_RPAREN,
      sym_attribute_name,
  [1200] = 2,
    ACTIONS(228), 1,
      anon_sym_SPACE,
    ACTIONS(230), 2,
      anon_sym_RPAREN,
      sym_attribute_name,
  [1208] = 2,
    ACTIONS(232), 1,
      anon_sym_SPACE,
    ACTIONS(234), 2,
      anon_sym_RPAREN,
      sym_attribute_name,
  [1216] = 2,
    ACTIONS(236), 1,
      anon_sym_SPACE,
    ACTIONS(238), 2,
      anon_sym_RPAREN,
      sym_attribute_name,
  [1224] = 2,
    ACTIONS(240), 1,
      anon_sym_SPACE,
    ACTIONS(242), 2,
      anon_sym_RPAREN,
      sym_attribute_name,
  [1232] = 3,
    ACTIONS(244), 1,
      anon_sym_SQUOTE,
    ACTIONS(246), 1,
      anon_sym_DQUOTE,
    STATE(67), 1,
      sym_quoted_attribute_value,
  [1242] = 2,
    ACTIONS(248), 1,
      anon_sym_DQUOTE,
    ACTIONS(250), 1,
      sym__html_identifier,
  [1249] = 2,
    ACTIONS(248), 1,
      anon_sym_SQUOTE,
    ACTIONS(252), 1,
      sym__html_identifier,
  [1256] = 2,
    ACTIONS(254), 1,
      sym__text,
    STATE(37), 1,
      sym_text_content,
  [1263] = 2,
    ACTIONS(256), 1,
      sym__text,
    STATE(48), 1,
      sym_text_content,
  [1270] = 2,
    ACTIONS(254), 1,
      sym__text,
    STATE(26), 1,
      sym_text_content,
  [1277] = 2,
    ACTIONS(256), 1,
      sym__text,
    STATE(42), 1,
      sym_text_content,
  [1284] = 1,
    ACTIONS(215), 2,
      anon_sym_RPAREN,
      sym_attribute_name,
  [1289] = 2,
    ACTIONS(258), 1,
      sym__text,
    ACTIONS(260), 1,
      sym__newline,
  [1296] = 2,
    ACTIONS(254), 1,
      sym__text,
    STATE(29), 1,
      sym_text_content,
  [1303] = 2,
    ACTIONS(256), 1,
      sym__text,
    STATE(40), 1,
      sym_text_content,
  [1310] = 2,
    ACTIONS(256), 1,
      sym__text,
    STATE(45), 1,
      sym_text_content,
  [1317] = 2,
    ACTIONS(254), 1,
      sym__text,
    STATE(30), 1,
      sym_text_content,
  [1324] = 1,
    ACTIONS(262), 1,
      anon_sym_SQUOTE,
  [1328] = 1,
    ACTIONS(264), 1,
      sym_ruby_expression,
  [1332] = 1,
    ACTIONS(266), 1,
      ts_builtin_sym_end,
  [1336] = 1,
    ACTIONS(262), 1,
      anon_sym_DQUOTE,
  [1340] = 1,
    ACTIONS(268), 1,
      sym__newline,
  [1344] = 1,
    ACTIONS(270), 1,
      sym__newline,
  [1348] = 1,
    ACTIONS(272), 1,
      sym__newline,
  [1352] = 1,
    ACTIONS(274), 1,
      sym__newline,
  [1356] = 1,
    ACTIONS(276), 1,
      sym__text,
  [1360] = 1,
    ACTIONS(278), 1,
      sym_ruby_expression,
  [1364] = 1,
    ACTIONS(280), 1,
      sym__newline,
  [1368] = 1,
    ACTIONS(282), 1,
      sym__text,
  [1372] = 1,
    ACTIONS(284), 1,
      sym__text,
  [1376] = 1,
    ACTIONS(286), 1,
      sym__text,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 40,
  [SMALL_STATE(4)] = 72,
  [SMALL_STATE(5)] = 112,
  [SMALL_STATE(6)] = 152,
  [SMALL_STATE(7)] = 182,
  [SMALL_STATE(8)] = 222,
  [SMALL_STATE(9)] = 254,
  [SMALL_STATE(10)] = 280,
  [SMALL_STATE(11)] = 306,
  [SMALL_STATE(12)] = 331,
  [SMALL_STATE(13)] = 356,
  [SMALL_STATE(14)] = 381,
  [SMALL_STATE(15)] = 406,
  [SMALL_STATE(16)] = 426,
  [SMALL_STATE(17)] = 446,
  [SMALL_STATE(18)] = 466,
  [SMALL_STATE(19)] = 486,
  [SMALL_STATE(20)] = 506,
  [SMALL_STATE(21)] = 526,
  [SMALL_STATE(22)] = 546,
  [SMALL_STATE(23)] = 560,
  [SMALL_STATE(24)] = 578,
  [SMALL_STATE(25)] = 592,
  [SMALL_STATE(26)] = 610,
  [SMALL_STATE(27)] = 624,
  [SMALL_STATE(28)] = 638,
  [SMALL_STATE(29)] = 656,
  [SMALL_STATE(30)] = 670,
  [SMALL_STATE(31)] = 684,
  [SMALL_STATE(32)] = 698,
  [SMALL_STATE(33)] = 712,
  [SMALL_STATE(34)] = 726,
  [SMALL_STATE(35)] = 744,
  [SMALL_STATE(36)] = 762,
  [SMALL_STATE(37)] = 780,
  [SMALL_STATE(38)] = 794,
  [SMALL_STATE(39)] = 814,
  [SMALL_STATE(40)] = 834,
  [SMALL_STATE(41)] = 846,
  [SMALL_STATE(42)] = 858,
  [SMALL_STATE(43)] = 870,
  [SMALL_STATE(44)] = 882,
  [SMALL_STATE(45)] = 894,
  [SMALL_STATE(46)] = 906,
  [SMALL_STATE(47)] = 918,
  [SMALL_STATE(48)] = 938,
  [SMALL_STATE(49)] = 950,
  [SMALL_STATE(50)] = 962,
  [SMALL_STATE(51)] = 974,
  [SMALL_STATE(52)] = 986,
  [SMALL_STATE(53)] = 998,
  [SMALL_STATE(54)] = 1018,
  [SMALL_STATE(55)] = 1035,
  [SMALL_STATE(56)] = 1052,
  [SMALL_STATE(57)] = 1069,
  [SMALL_STATE(58)] = 1086,
  [SMALL_STATE(59)] = 1103,
  [SMALL_STATE(60)] = 1120,
  [SMALL_STATE(61)] = 1130,
  [SMALL_STATE(62)] = 1140,
  [SMALL_STATE(63)] = 1150,
  [SMALL_STATE(64)] = 1163,
  [SMALL_STATE(65)] = 1176,
  [SMALL_STATE(66)] = 1189,
  [SMALL_STATE(67)] = 1200,
  [SMALL_STATE(68)] = 1208,
  [SMALL_STATE(69)] = 1216,
  [SMALL_STATE(70)] = 1224,
  [SMALL_STATE(71)] = 1232,
  [SMALL_STATE(72)] = 1242,
  [SMALL_STATE(73)] = 1249,
  [SMALL_STATE(74)] = 1256,
  [SMALL_STATE(75)] = 1263,
  [SMALL_STATE(76)] = 1270,
  [SMALL_STATE(77)] = 1277,
  [SMALL_STATE(78)] = 1284,
  [SMALL_STATE(79)] = 1289,
  [SMALL_STATE(80)] = 1296,
  [SMALL_STATE(81)] = 1303,
  [SMALL_STATE(82)] = 1310,
  [SMALL_STATE(83)] = 1317,
  [SMALL_STATE(84)] = 1324,
  [SMALL_STATE(85)] = 1328,
  [SMALL_STATE(86)] = 1332,
  [SMALL_STATE(87)] = 1336,
  [SMALL_STATE(88)] = 1340,
  [SMALL_STATE(89)] = 1344,
  [SMALL_STATE(90)] = 1348,
  [SMALL_STATE(91)] = 1352,
  [SMALL_STATE(92)] = 1356,
  [SMALL_STATE(93)] = 1360,
  [SMALL_STATE(94)] = 1364,
  [SMALL_STATE(95)] = 1368,
  [SMALL_STATE(96)] = 1372,
  [SMALL_STATE(97)] = 1376,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(93),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(57),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(63),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(92),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(97),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__children, 2, 0, 0),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [39] = {.entry = {.count = 1, .reusable = false}}, SHIFT(85),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [45] = {.entry = {.count = 1, .reusable = false}}, SHIFT(55),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [49] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [51] = {.entry = {.count = 1, .reusable = false}}, SHIFT(95),
  [53] = {.entry = {.count = 1, .reusable = false}}, SHIFT(96),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [57] = {.entry = {.count = 1, .reusable = false}}, SHIFT(58),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [61] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__children_repeat1, 2, 0, 0),
  [67] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__children_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [70] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__children_repeat1, 2, 0, 0), SHIFT_REPEAT(95),
  [73] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__children_repeat1, 2, 0, 0), SHIFT_REPEAT(96),
  [76] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__children_repeat1, 2, 0, 0), SHIFT_REPEAT(85),
  [79] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__children_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [82] = {.entry = {.count = 1, .reusable = false}}, SHIFT(54),
  [84] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [86] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [88] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [90] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [92] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [96] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [99] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(92),
  [102] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(97),
  [105] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(93),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 0),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag, 4, 0, 0),
  [114] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag, 4, 0, 0),
  [116] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ruby_block_output, 3, 0, 0),
  [120] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_ruby_block_output, 3, 0, 0),
  [122] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_tag_repeat1, 2, 0, 0),
  [124] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_tag_repeat1, 2, 0, 0),
  [126] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_tag_repeat1, 2, 0, 0), SHIFT_REPEAT(17),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag, 5, 0, 0),
  [131] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag, 5, 0, 0),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag, 2, 0, 0),
  [135] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag, 2, 0, 0),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag, 3, 0, 0),
  [139] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag, 3, 0, 0),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ruby_block_run, 3, 0, 0),
  [143] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_ruby_block_run, 3, 0, 0),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ruby_block_run, 4, 0, 0),
  [147] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_ruby_block_run, 4, 0, 0),
  [149] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [151] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ruby_block_output, 4, 0, 0),
  [153] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_ruby_block_output, 4, 0, 0),
  [155] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_text_content, 1, 0, 0),
  [157] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_text_content, 1, 0, 0),
  [159] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag, 6, 0, 0),
  [161] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag, 6, 0, 0),
  [163] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ruby_interpolation, 2, 0, 0),
  [165] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_ruby_interpolation, 2, 0, 0),
  [167] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__children, 3, 0, 0),
  [169] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__children, 3, 0, 0),
  [171] = {.entry = {.count = 1, .reusable = false}}, SHIFT(56),
  [173] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [175] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [177] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_doctype, 3, 0, 0),
  [179] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_doctype, 3, 0, 0),
  [181] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_doctype, 2, 0, 0),
  [183] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_doctype, 2, 0, 0),
  [185] = {.entry = {.count = 1, .reusable = false}}, SHIFT(59),
  [187] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [189] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [191] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [193] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [195] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [197] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [199] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_html_attributes, 3, 0, 0),
  [201] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_html_attributes, 3, 0, 0),
  [203] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_html_attributes, 2, 0, 0),
  [205] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_html_attributes, 2, 0, 0),
  [207] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_attributes, 1, 0, 0),
  [209] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attributes, 1, 0, 0),
  [211] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [213] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [215] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_html_attributes_repeat1, 2, 0, 0),
  [217] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_html_attributes_repeat1, 2, 0, 0), SHIFT_REPEAT(66),
  [220] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [222] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 1, 0, 0),
  [224] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_attribute, 1, 0, 0),
  [226] = {.entry = {.count = 1, .reusable = false}}, SHIFT(71),
  [228] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 3, 0, 0),
  [230] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_attribute, 3, 0, 0),
  [232] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [234] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_html_attributes_repeat1, 1, 0, 0),
  [236] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_attribute_value, 3, 0, 0),
  [238] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_quoted_attribute_value, 3, 0, 0),
  [240] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_attribute_value, 2, 0, 0),
  [242] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_quoted_attribute_value, 2, 0, 0),
  [244] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [246] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [248] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [250] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [252] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [254] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [256] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [258] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [260] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [262] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [264] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [266] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [268] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [270] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [272] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [274] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [276] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [278] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [280] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [282] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [284] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [286] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token__newline = 0,
  ts_external_token__indent = 1,
  ts_external_token__dedent = 2,
  ts_external_token_ruby_attributes = 3,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token__newline] = sym__newline,
  [ts_external_token__indent] = sym__indent,
  [ts_external_token__dedent] = sym__dedent,
  [ts_external_token_ruby_attributes] = sym_ruby_attributes,
};

static const bool ts_external_scanner_states[7][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token__newline] = true,
    [ts_external_token__indent] = true,
    [ts_external_token__dedent] = true,
    [ts_external_token_ruby_attributes] = true,
  },
  [2] = {
    [ts_external_token__newline] = true,
    [ts_external_token_ruby_attributes] = true,
  },
  [3] = {
    [ts_external_token__newline] = true,
    [ts_external_token__dedent] = true,
  },
  [4] = {
    [ts_external_token__newline] = true,
  },
  [5] = {
    [ts_external_token__newline] = true,
    [ts_external_token__indent] = true,
    [ts_external_token__dedent] = true,
  },
  [6] = {
    [ts_external_token__indent] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_haml_external_scanner_create(void);
void tree_sitter_haml_external_scanner_destroy(void *);
bool tree_sitter_haml_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_haml_external_scanner_serialize(void *, char *);
void tree_sitter_haml_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_haml(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_haml_external_scanner_create,
      tree_sitter_haml_external_scanner_destroy,
      tree_sitter_haml_external_scanner_scan,
      tree_sitter_haml_external_scanner_serialize,
      tree_sitter_haml_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
